### ISSUE TITLE
工作流文件默认保存在哪的呢？

### ISSUE THREAD

**Issue by billowssun** [11cafe/comfyui-workspace-manager#10]

**Comment by Weixuanf** [comment]
hi working on auto saving workflows into selected dir!
正在做这个功能！之后可以自己选择export的目录，会自动保存到那个目录！请等我几天时间！谢谢！欢迎意见建议

**Comment by Weixuanf** [comment]
hi this feature is now added, all your workflows are saved into ComfyUI/my_workflows

**Comment by billowssun** [comment]
thank you

On Dec 10, 2023, at 22:58, Weixuan Fu ***@***.***> wrote:



hi working on auto saving workflows into selected dir!
正在做这个功能！之后可以自己选择export的目录，会自动保存到那个目录！请等我几天时间！谢谢！欢迎意见建议
