### ISSUE TITLE
📊Vote: Should the default "Load" button in ComfyUI overwrite your current flow or create new flow with the file name?

### ISSUE THREAD

**Issue by Weixuanf** [11cafe/comfyui-workspace-manager#100]
how do peopel feel about the default "Load" button in ComfyUI should behave with workspace manager? should it load the workflow in a brand new flow with the file name or should it overwrite your current flow

im thinking we should let it overwrite your current flow (you can discard unsaved changes if you don't like it) 
then have a separate button of "Open file" that will create a new flow and show it without overwriting the current
How do y'all feel about it?

**Comment by Weixuanf** [comment]
> add a button in setting so that user can switch it(?

Good suggestion! Makes everyone happy

**Comment by chflame163** [comment]
> add a button in setting so that user can switch it(?在设置中添加一个按钮，以便用户可以切换它（？

good idea!

**Comment by Weixuanf** [comment]
in latest version,
both load and drag and drop will create new flow in default, you can change drag drop to overwrite cur workflow in settings
