### ISSUE TITLE
feature request - make topbar position configurable

### ISSUE THREAD

**Issue by Weixuanf** [11cafe/comfyui-workspace-manager#12]
> 2) The buttons cover the top-left corner, where I have a info box that displays running node's status. It is now blocked. Could the location of the buttons be configured?

from DC channel

**Comment by rovo79** [comment]
Here's an example image for reference:
<img width="429" alt="image" src="https://github.com/11cafe/comfyui-workspace-manager/assets/117691/810b5398-ba1f-4905-9c49-a2891f27d844">

**Comment by Weixuanf** [comment]
<img width="331" alt="Screenshot 2023-12-27 at 11 23 16 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/7b574c73-0701-47b4-9168-937673c5f963">

in new version you can drag here to change the position of the topbar
