### ISSUE TITLE
【建议】可否提供和系统UI颜色相同的页面颜色

### ISSUE THREAD

**Issue by amimi818** [11cafe/comfyui-workspace-manager#120]
很棒的插件！

建议菜单页面颜色可以和系统或comfyui保持一致，或者可以自定义选择（深色/浅色）。

不好意思，刚发现已经实现了。

**Comment by Weixuanf** [comment]
haha sorry it was a bit hided, i should probably write some docs about it
哈哈不好意思这个选项可能有点儿不明显，我之后应该加一些docs，这样大家更好了解怎么使用

谢谢你的支持和建议！
<img width="554" alt="Screenshot 2024-01-15 at 2 49 23 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/3ad02caf-9968-4382-be96-3dce0be21d08">
