### ISSUE TITLE
Two suggestions

### ISSUE THREAD

**Issue by AlexanderDash** [11cafe/comfyui-workspace-manager#13]
Two suggestions
1、 Can I turn off the animation when the sidebar pops up
2、 I have created a new workflow named "Gini too beautiful", but I cannot find the local folder for this workflow named "Gini too beautiful" Please tell me where it is. If your code doesn't separate these workflows, it would be too troublesome
I tried to find the Gini Taimei. json file, but I couldn't find it. I found
In
ComfyUI \ custom_ Nodes \ comfyui workspace manager \ backup \ workflows
ComfyUI \ custom_ The JSON files in the nodes \ comfyui workspace manager \ db folder cannot be directly dragged into the browser window
![QQ浏览器截图20231210222652](https://github.com/11cafe/comfyui-workspace-manager/assets/134115886/5e7d862b-a3aa-4910-a828-145132684522)

**Comment by Weixuanf** [comment]
hi working on exporting functions! will come out soon!

**Comment by Weixuanf** [comment]
Hi in the new version it all you workflows are automatically output to a folder in /ComfyUI/my_workflows
later I will enable customize this directory.

for 1)disable animations, I added to my dev plan, will support it later

**Comment by Weixuanf** [comment]
1) in the new update, the animation is disabled now
2) we have /ComfyUI/my_workflows now to store all your workflows
