### ISSUE TITLE
Menu is missing

### ISSUE THREAD

**Issue by koko93s** [11cafe/comfyui-workspace-manager#133]
Hello!  

The Workspace Manager menu seems to have gone on holiday on my installation.  I have tried updating, deleting and reinstalling a fresh git clone and it still will not come back 

I see the following in the Comfyui console during startup:  ### Loading: Workspace Manager (V1.0.0)

Any suggestions?

Thanks!

**Comment by brianjz** [comment]
Same here. Worked yesterday, but did "git pull" Comfy today. Maybe something on that end changed.

**Comment by koko93s** [comment]
Glad to know it's not just me!  Suffer with me!

**Comment by oliverban** [comment]
Yepp, this happened to me as well! Just came in here to check! :P

**Comment by DavidEBell** [comment]
Lost this wonderful functionality with latest set of updates. No errors displayed on console during startup.

**Comment by darkpixel** [comment]
Definitely seems like Chrome is failing to load some javascript:

![Screenshot from 2024-01-18 12-39-48](https://github.com/11cafe/comfyui-workspace-manager/assets/158380/ba2759a5-2984-4d70-abd8-ebac17842aa9)

**Comment by koko93s** [comment]
Nice catch @hsreina .  I did the npm build and it seems to work now.  Nice hack until officially fixed!  :D

**Comment by darkpixel** [comment]
Your build finished already @koko93s ?  Sheesh.  I have a 8-core 3.6 GHz CPU with 128 GB RAM and an m.2 drive...it's been building for ~10 minutes now.  I'd probably be envious of your machine. ;)

**Comment by koko93s** [comment]
Eek @darkpixel .  I'm running on a laptop  i7-9750H, 6 core 4ghz @ turbo and 32gb ram.  Build finished in 8.9seconds.... n Your times don't seem right!

**Comment by hsreina** [comment]
@darkpixel build take ~8seconds with a normal computer

**Comment by darkpixel** [comment]
I suspect node wonkiness unrelated to this issue.  Time to dust off my basic node knowledge and get to the bottom of this.

![Screenshot from 2024-01-18 13-31-19](https://github.com/11cafe/comfyui-workspace-manager/assets/158380/176a22b6-b88d-4f9b-93cc-d21e71e2950d)

**Comment by hsreina** [comment]
@darkpixel don't know if it can help you, but I used those versions of npm and node:
node version: v20.10.0
npm version: 10.2.3

**Comment by darkpixel** [comment]
Thanks @hsreina, I was just wondering what version you were using.
I'm a bit behind.  I'm still running Linux Mint 21.1 because it's been so stable.  I guess it's time to upgrade. :)

**Comment by hsreina** [comment]
@darkpixel maybe you should try to uses '[nvm](https://github.com/nvm-sh/nvm)' to temporary switch to a specific version of node

**Comment by Weixuanf** [comment]
🤦‍♀️ ok i've just fixed it in main branch. If you update you should see it appear again

 im so sorry about it, I accidentally deleted the build files when trying to fix a bug in main branch. I need to set git hooks for maintain separate gitigore files so it won't happen again🥹

**Comment by koko93s** [comment]
@Weixuanf No worries!  Thanks for fixing it!  Cheers.🍻
