### ISSUE TITLE
Failed to fetch dynamically imported module?

### ISSUE THREAD

**Issue by darkpixel** [11cafe/comfyui-workspace-manager#134]
I just stumbled across your project while searching in Comfy UI Manager.

I installed it and restarted ComfyUI, then did a CTRL+F5 to refresh the browser, but nothing seems to have changed in the interface.

I popped open DevTools, and it looks like it might be failing to load a library related to Workspace Manager.

![Screenshot from 2024-01-18 12-39-48](https://github.com/11cafe/comfyui-workspace-manager/assets/158380/f64bc70d-755b-4250-b4bb-6dc2972f5598)

I installed it a few minutes ago, so I'm on commit f201ac5af4e8225acc45ff81ff5b073672b518f5

**Comment by koko93s** [comment]
HI!  Seems like the same problem as #133 , maybe add that info over there?

**Comment by darkpixel** [comment]
Yup--that seems like a dupe.  I'll toss my screenshot in over there and close this one.  Thanks @koko93s !
