### ISSUE TITLE
Two errors were found

### ISSUE THREAD

**Issue by wibur0620** [11cafe/comfyui-workspace-manager#137]
I have currently observed two issues with this plugin:
1：After using one workflow and switching to another, it seems that the model from the previous workflow is not unloaded. This results in very high GPU memory usage when running inference in the current workflow.
2：Changes made within the workflow, such as modifying the detection model or fixing it using the comfyui-reactor-node plugin, are sometimes ineffective. Although the interface reflects the changes, the actual results displayed in the terminal do not reflect any modifications. Eventually, the output image also shows that the model hasn't been updated. It appears that after using this plugin, comfyui assumes no changes have been made and does not run inference.

**Comment by Weixuanf** [comment]
> 1：After using one workflow and switching to another, it seems that the model from the previous workflow is not unloaded.

Do you see these issues in ComfUI itself with no workspace manager installed?  I wonder if this issue is related to workspace manager or its a issue of ComfyUI itself?
so trying to test this using google colab, 
### first no workspace installed, only comfyui, comfyui-manager, crystools for GPU monitor:
screen recording https://youtu.be/Ot7Chl2Go6M
i first loaded a stable video diffusion workflow, using **sd1.5 and svd.safetensor** models, after running that workflow to create a gif, the vram is at **87%**
then, i swtiched to the default workflow (using ComfyUI's default load button), it uses **only sd1.5** model, and i checked the vram usage, its still at 87%, then i ran inference, after inference done, it still at 87%, the same as before when using svd.safetensor model (which is 9gb), therefore i feel like ComfyUI itself doesn't do model offloading? so it may not be a problem of our plugin. 

But I really hear more insights from you, or could you suggest other ways for me to reproduce and test this issue? 

Thank you very much for your feedbacks! I really hope to make it work for you!

**Comment by wibur0620** [comment]
I feel extremely powerless to reproduce the issue because it always arises suddenly. Previously, when I disabled this plugin, during the deactivation period, the problem did not occur. However, whenever I use this plugin, the issue inexplicably surfaces. I cannot identify any pattern for its occurrence. For complex workflows, once this error appears, it requires a considerable amount of effort and time to troubleshoot. My approach is to either directly restart or stop the plugin, and only after completing the workflow do I dare to use the plugin again. I am willing to carefully observe and document the recurrence of this issue and provide you with recordings later.

**Comment by Weixuanf** [comment]
>  Previously, when I disabled this plugin, during the deactivation period, the problem did not occur. However, whenever I use this plugin, the issue inexplicably surfaces.

Hi are you talking about the issue 1) model not unloaded (high GPU memory usage) or issue 2)modifying the detection model or fixing it using the comfyui-reactor-node plugin, are sometimes ineffective. ? or both?

for issue 2) I found this reactor faceswap workflow that I'll try to use to reproduce https://openart.ai/workflows/pademelon_boring_44/faceswap-upscaler-reactor/k4AKY0e2HnNF16RiMQDU
issue you are talking about is that changing the swap_model in the UI like below, will not take effect when you actually run this prompt? How do you tell this, is it by checking the output image's pngInfo metadata's prompt vale?
<img width="436" alt="Screenshot 2024-01-20 at 11 14 51 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/fa4a53a6-989c-4f77-a2d8-e23384e80031">

> such as modifying the detection model or fixing it using the comfyui-reactor-node plugin, are sometimes ineffective.
for the detection model,  which node are you referring to, or could you give a very simple workflow that may be able to used to reproduce the detection model issue?

I'll try to reproduce this issue as best as i can, but prob need a bit help from you!

and when you see this issue occurs, if you could screenshot or copy the python server logs, and in your browser press F12 or rightclieck -> Inspect -> Console to get the browser side console logs, especially see if there is any error logs! That would be helpful too!

**Comment by wibur0620** [comment]
A new problem has arisen. Your plug-in cannot be updated.

Fetch error: D:\AI\ComfyUI\custom_nodes\comfyui-workspace-manager

Cmd('git') failed due to: exit code(1)
  cmdline: git fetch -v -- origin
  stderr: 'error: cannot lock ref 'refs/remotes/origin/feat/model-list-refresh': is at 3ddf59e4b24c016b938c8d2dc346c756c28a5f33 but expected efe51bf9e7aabf1e222cfe61c30fab044d282184'
CUSTOM NODE CHECK: Error

Fetching done.

**Comment by wibur0620** [comment]
PS D:\AI\ComfyUI\custom_nodes\comfyui-workspace-manager> git pull
error: cannot lock ref 'refs/remotes/origin/feat/model-list-refresh': is at 3ddf59e4b24c016b938c8d2dc346c756c28a5f33 but expected efe51bf9e7aabf1e222cfe61c30fab044d282184
From https://github.com/11cafe/comfyui-workspace-manager
 ! efe51bf..3ddf59e  feat/model-list-refresh -> origin/feat/model-list-refresh  (unable to update local ref)
PS D:\AI\ComfyUI\custom_nodes\comfyui-workspace-manager>

**Comment by Weixuanf** [comment]
> I'm sorry, I'm also having this issue when I'm not using this plugin. I redeployed comfui for this purpose.,So far there is no such problem.,It doesn't seem like it's your plugin's problem.,Sorry.。 Troubled you,

no worries thanks for letting me know!

> PS D:\AI\ComfyUI\custom_nodes\comfyui-workspace-manager> git pull error: cannot lock ref 'refs/remotes/origin/feat/model-list-refresh': is at [3ddf59e](https://github.com/11cafe/comfyui-workspace-manager/commit/3ddf59e4b24c016b938c8d2dc346c756c28a5f33) but expected [efe51bf](https://github.com/11cafe/comfyui-workspace-manager/commit/efe51bf9e7aabf1e222cfe61c30fab044d282184) From https://github.com/11cafe/comfyui-workspace-manager ! [efe51bf](https://github.com/11cafe/comfyui-workspace-manager/commit/efe51bf9e7aabf1e222cfe61c30fab044d282184)..[3ddf59e](https://github.com/11cafe/comfyui-workspace-manager/commit/3ddf59e4b24c016b938c8d2dc346c756c28a5f33) feat/model-list-refresh -> origin/feat/model-list-refresh (unable to update local ref) PS D:\AI\ComfyUI\custom_nodes\comfyui-workspace-manager>

Maybe try to delete the comfyui-workspace-manager folder and reinstall, but before you delete, make a copy of this entire folder somewhere else: `comfyui-workspace-manager/db`, if after reinstall, you see some data loss, you can just copy back this entire db folder back into it. Theoretically you shouldn't experience any data loss by deleting and reinstalling, but just in case.
