### ISSUE TITLE
please turn off autosaving 

### ISSUE THREAD

**Issue by Ulf3000** [11cafe/comfyui-workspace-manager#141]
this is the one problem which makes it almost unusable, or you gotta be careful the whole time. of course i want to save the changes AFTER i did modifications , with your addon it saves all the time so im forced to save a new workflow BEFORE even if i just experiment.. no other porgram ever did it this way for good reasons

**Comment by Weixuanf** [comment]
Hi you can disable autosave in settings. Uncheck this "Enable Auto save workflow" option


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Alex Mehler ***@***.***>
Sent: Monday, January 22, 2024 2:37:15 AM
To: 11cafe/comfyui-workspace-manager ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [11cafe/comfyui-workspace-manager] please turn off autosaving (Issue #141)


this is the one problem which makes it almost unusable, or you gotta be careful the whole time. of course i want to save the changes after i did modifications , with your addon it saves all the time so im forced to save a new workflow even if i just experiment.. no other porgram ever did it this way for good reasons

**Comment by Weixuanf** [comment]
<img width="502" alt="Screenshot 2024-01-22 at 2 33 00 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/982e7ee4-fecc-4ecb-9b95-57d797bed0d6">

**Comment by darkpixel** [comment]
Thank God for the disable button.

Manually saving works.

Automatic saving lags the web interface to a halt and frequently throws errors:

![Screenshot from 2024-03-17 18-39-36](https://github.com/11cafe/comfyui-workspace-manager/assets/158380/eff846b7-b13f-4949-9ca9-22c92db74229)

**Comment by Weixuanf** [comment]
Hi very sorry there were some bugs with auto save mode a few days ago. Now it should be fixed. Feel free to switch on auto save and if it’s still troublesome, please let me know!

Thank you!
________________________________

**Comment by darkpixel** [comment]
No worries--most developers wouldn't think to have a feature-gate for a new feature. :)
