### ISSUE TITLE
feature request: workflow names as tabtitles

### ISSUE THREAD

**Issue by Ulf3000** [11cafe/comfyui-workspace-manager#143]
hi i modded your app.tsx and added this 

document.title = `ComfyUI - ${curWorkflow.name ?? "Untitled"}`;

in line 161 in checkIsDirty function.. 

looks like this 
![grafik](https://github.com/11cafe/comfyui-workspace-manager/assets/10765339/0d369b30-6c57-420d-893c-53fb1c28f5e8)

very handy .. 

i can mod it myself after each update of course but its a nice feature and would be nice if you implement it in your programming style .. i just put it there becasue getWorkflow(curFlowID.current) is called already and just updating the title on workflow load will be overridden after a while 

edit: 
or maybe even better without "comfyui" ??
![grafik](https://github.com/11cafe/comfyui-workspace-manager/assets/10765339/e11c5afd-d5bb-4eab-9bdf-e8a0dfa3ba62)

**Comment by Ulf3000** [comment]
since workflow names can be long, i think without "comfyui -" is better now. the icon is pretty unique and its probabnly best to create a chrome profile just for comfy with just comfy tabs anyways.

**Comment by Weixuanf** [comment]
. the icon is pretty unique 
i think this icon only comes with the Custom Scripts plugin, its not default by comfyui 🫠

**Comment by Ulf3000** [comment]
> > the icon is pretty unique
> 
> i think this icon only comes with the Custom Scripts plugin, its not default by comfyui 🫠... or not? correct me if I'm wrong!

which script ? does it? i have this little anime cat girl as icon, i think that was there from the get go

 if you are at it maybe you could also create an icon from the most recent generated image in each flow for each tab 
 
 here this is how Ill setup my "AI Toolbox" from now on (or very similar at least) 
 
 
![grafik](https://github.com/11cafe/comfyui-workspace-manager/assets/10765339/abe26e01-4145-40ec-88df-c658793fae63)

**Comment by Weixuanf** [comment]
woww your setup looks dope my friend! I should get that side bar tabs too 💯 I always find myself overwhelmed by 10000 tabs in my browser

yeah verified again, that golden angel like girl icon is from this scrip:
https://github.com/pythongosssss/ComfyUI-Custom-Scripts

without that plugin, it has no favicon
<img width="499" alt="Screenshot 2024-01-25 at 2 46 38 AM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/414c6873-8f5d-4e48-9614-88afd5811538">

**Comment by Ulf3000** [comment]
another thing: when i reload a browser session (or just restore  a closed tab) comfy will just load the default workflow in each tab .. wouldnt it be possible to save the workflow id to a cookie/localstorage/sessiostorage/whatever and read it on restore and load the right workflows ? im 90% confident thats possible and not even that hard , will try to look into it tommorrow.

**Comment by Weixuanf** [comment]
Hi in the beta version this is solved by adding the workflow id to the url hash, it’s like ***@***.***

So every time you refresh, the tab should reload the right workflow

BTW are u interested in previewing out beta version ? We have some exciting new features!
https://github.com/11cafe/comfyui-workspace-manager/tree/main#beta-preview

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Weixuanf** [comment]
If you decided to checkout beta, make sure you make a copy of your current comfyui-workspace-manager folder somewhere else, just in case anything unexpected happens

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Ulf3000** [comment]
> BTW are u interested in previewing out beta version ? We have some exciting new features!

sure! will check it out

**Comment by Weixuanf** [comment]
Great! Let me know if that works for you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Ulf3000** [comment]
ok i tested it , the workflow restores fine when a tab is restored .. but after a browser restart the most recent flow is just loaded into every comfy ui tab. On Chrome

**Comment by Weixuanf** [comment]
Oh that’s weird. How did you restart the browser? Just closing all windows?

Before and after restart, does your url looks like:
***@***.***

If it looks like just "http://127.0.0.1:8188/" then it will load the most recent workflow
It has to have the id in the url to load the certain workflow

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Weixuanf** [comment]
<img width="386" alt="Screenshot 2024-01-26 at 6 53 24 AM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/b7abbf3b-5499-4e21-8fb0-d5140ebe0f86">
make sure you clicked this "Open in new tab" button when opening a workflow

**Comment by Ulf3000** [comment]
> <img alt="Screenshot 2024-01-26 at 6 53 24 AM" width="386" src="https://private-user-images.githubusercontent.com/18367033/299828705-b7abbf3b-5499-4e21-8fb0-d5140ebe0f86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTQxNzksIm5iZiI6MTcwNjI1Mzg3OSwicGF0aCI6Ii8xODM2NzAzMy8yOTk4Mjg3MDUtYjdhYmJmM2ItNTQ5OS00ZTIxLThmYjAtZDUxNDBlYmUwZjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA3MjQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZjUwNzNjNTFiYjQyZDZmYmU4Y2ZkMTg1MDZiM2VjNzkwZjQ5NDdhZjQ0ZmFkZDQzM2NjMWM0NDhiNzEwNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gUbWzeRD5rP53qtMfOoBOWtj2OksnEdPw9jLIzRAE90"> make sure you clicked this "Open in new tab" button when opening a workflow

it were only the old tabs from before installing the beta, after closing them and loading new tabs it worked   .. 

**i tested if the string changes on new flow, flow load , restart, restore tab .. seems to work nicely !**

one improvement could be that when closing a tab or the browser, it will alert you that the changes are discarded .. i think using the message to ask for saving with yes/no would be nice.

**Comment by Weixuanf** [comment]
> one improvement could be that when closing a tab or the browser, it will alert you that the changes are discarded .. i think using the message to ask for saving with yes/no would be nice.

like this?
<img width="778" alt="Screenshot 2024-01-26 at 9 49 05 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/202db117-a891-4f58-b32d-0f3b9c842bd1">

I just added this new dev branch, not yet launched ^^

**Comment by Weixuanf** [comment]
fixed in latest version
