### ISSUE TITLE
Breaks copy and pasting of nodes

### ISSUE THREAD

**Issue by mordbane** [11cafe/comfyui-workspace-manager#15]
I must have something conflicting but this breaks copy and pasting of nodes for me.  It seems like whatever .json gets loaded in the clipboard gets stuck.  Selecting nodes and using Ctrl-C  doesn't reload anything into the clipboard.  This is the error I'm seeing in the console.  Removing the workspace manager restores the function.

![image](https://github.com/11cafe/comfyui-workspace-manager/assets/4472440/b5b999f6-e934-459f-8f55-ca641c1f9e42)

**Comment by Weixuanf** [comment]
looking at it! sorry about this

**Comment by Weixuanf** [comment]
ok the problem is caused by `ChakraProvider`, if i remove ChakraProvider from main.ts then it will work. I have no idea why ChakraProvider could affect clipboard. 
But I may have to switch to other UI frameworks. This may take 1 day of effort to finish....😕

**Comment by Weixuanf** [comment]
i just pushed the change that should fix this: https://github.com/11cafe/comfyui-workspace-manager/commit/f1e2ebf9208e3ee43db679c607338a5a38c5f1e1
please pull the latest update and see if the problem goes away. please let me know!!

**Comment by mordbane** [comment]
Looking good!  Testing continues...
