### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by PabloMontero** [11cafe/comfyui-workspace-manager#150]
Is it possible to have a nested folder structure?

Apparently not, for any reason?

Thank you, this project is in my top 3.

**Comment by Weixuanf** [comment]
hi we do have this feature in beta
and many other new features, you are welcome to test our beta branch! you can follow the instructions here:

https://github.com/11cafe/comfyui-workspace-manager/tree/main?tab=readme-ov-file#beta-preview


<img width="491" alt="Screenshot 2024-01-24 at 2 13 10 AM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/f9633fe1-dadc-450c-9ea6-86e973f19bee">

**Comment by PabloMontero** [comment]
Super, thanks!

**Comment by Weixuanf** [comment]
Actually we have this feature already in our latest version in main. you can just update to get it. you can create a nested folder like this:
<img width="404" alt="Screenshot 2024-01-25 at 7 33 13 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/f50df44b-d284-40a7-9b15-9eea1fce7e11">

but in beta we have more new features!
