### ISSUE TITLE
Generating Batches does not interact as expected with the Image Gallery

### ISSUE THREAD

**Issue by HaydenReeve** [11cafe/comfyui-workspace-manager#156]
Hello 👋

There is a troublesome bug with the image gallery when you generate images in batches.

See the following workflow:

![image](https://github.com/11cafe/comfyui-workspace-manager/assets/39004735/bef02731-8454-49f2-a3fa-0169ebbd0cf6)

When inspecting this output in the gallery, you would expect four images to display. Instead, you get one. Note that it is the _0004 version of the generation:

![image](https://github.com/11cafe/comfyui-workspace-manager/assets/39004735/8e48354f-f222-41f6-b62d-236c79e5265a)

The gallery does not capture three out of four of the generated images.

Then, by changing the workflow (in this instance I renamed the file from `test\test` to `test`, the following output is given. Note the gap between the `_0008` and `_0005` name tags:

Please note that I doubt there is correlation in changing the name, it's simply to refresh the workflow and to demonstrate behaviours with different names (such as in folders).

![image](https://github.com/11cafe/comfyui-workspace-manager/assets/39004735/22cfbead-9614-44cd-b988-6db2623e18cf)

The gallery does not capture two out of four of the generated images.

In this instance that this is expected behaviour, I would expect the tags to be next to each other, e.g.: `_0005` and `_0006`, or just `_0005`. 

The workflow used to generate this example is an extremely basic one, please find it here:

```json
{"last_node_id":9,"last_link_id":9,"nodes":[{"id":3,"type":"KSampler","pos":[870,180],"size":{"0":315,"1":262},"flags":{},"order":4,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":1},{"name":"positive","type":"CONDITIONING","link":4},{"name":"negative","type":"CONDITIONING","link":6},{"name":"latent_image","type":"LATENT","link":2}],"outputs":[{"name":"LATENT","type":"LATENT","links":[7],"slot_index":0}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[1107107286745394,"randomize",20,8,"euler","normal",1]},{"id":8,"type":"VAEDecode","pos":[1215,180],"size":{"0":210,"1":46},"flags":{},"order":5,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":7},{"name":"vae","type":"VAE","link":8}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[9],"slot_index":0}],"properties":{"Node name for S&R":"VAEDecode"}},{"id":7,"type":"CLIPTextEncode","pos":[420,390],"size":{"0":425.27801513671875,"1":180.6060791015625},"flags":{},"order":3,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":5}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[6],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["text, watermark"]},{"id":5,"type":"EmptyLatentImage","pos":[525,615],"size":{"0":315,"1":106},"flags":{},"order":0,"mode":0,"outputs":[{"name":"LATENT","type":"LATENT","links":[2],"slot_index":0}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[512,512,4]},{"id":4,"type":"CheckpointLoaderSimple","pos":[-15,180],"size":[405,105],"flags":{},"order":1,"mode":0,"outputs":[{"name":"MODEL","type":"MODEL","links":[1],"slot_index":0},{"name":"CLIP","type":"CLIP","links":[3,5],"slot_index":1},{"name":"VAE","type":"VAE","links":[8],"slot_index":2}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["SD\\Stylistic\\arthemyComics_v50.safetensors"]},{"id":6,"type":"CLIPTextEncode","pos":[420,180],"size":{"0":422.84503173828125,"1":164.31304931640625},"flags":{},"order":2,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":3}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[4],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["1girl, portrait, looking at viewer, spacesuit, space scenery, nasa, stars, floating in space,"]},{"id":9,"type":"SaveImage","pos":[1455,180],"size":[330,375],"flags":{},"order":6,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":9}],"properties":{},"widgets_values":["test"]}],"links":[[1,4,0,3,0,"MODEL"],[2,5,0,3,3,"LATENT"],[3,4,1,6,0,"CLIP"],[4,6,0,3,1,"CONDITIONING"],[5,4,1,7,0,"CLIP"],[6,7,0,3,2,"CONDITIONING"],[7,3,0,8,0,"LATENT"],[8,4,2,8,1,"VAE"],[9,8,0,9,0,"IMAGE"]],"groups":[],"config":{},"extra":{},"version":0.4}
```

This is reproducable in basic to complex workflows, and occurs regardless of the save file complexity (name, name with folders, name with folders and variables)

I have not yet had the change to test with a fresh install of ComfyUI, although I don't imagine this workflow should be affected. This was performed on the latest version of both Comfy and this plugin as of the time of this post.

**Comment by Weixuanf** [comment]
Thanks for reporting! I’ll take a look asap

**Comment by arslan2012** [comment]
For the life of me I could not reproduce the bug, here a screen record of me trying to reproduce it, tell me if I missed any steps

<div align="center">
  <a href="https://www.loom.com/embed/0c3f3cfcc9654652b1bc538d174b2f6c?sid=cb54a95a-0be8-4de7-9703-a11975b56690"><img src="https://cdn.loom.com/sessions/thumbnails/0c3f3cfcc9654652b1bc538d174b2f6c-with-play.gif" alt="IMAGE ALT TEXT"></a>
</div>

**Comment by HaydenReeve** [comment]
That is positively baffling. Alright, I'll endeavour to get a better info dump from my machine and then see if it's replicable on other machines here.

It may be environment-specific to some degree.

Cheers for looking into this, I'll follow up soon.

**Comment by HaydenReeve** [comment]
Alright, so what I did to follow up was wipe and refresh my requirements, update to the latest version, and it _seems_ to have started to work.

I'm not sure if that coincided with the new updates that have come through if it was perhaps an old requirement, or maybe even simply something else.

I think I'd be happy to suggest that if anyone else encounters this issue, just clean and reinstall with your requirements file and perhaps it may start working as expected.

As I can no longer reproduce this issue, I'll close this ticket.
