### ISSUE TITLE
Broken thumbnail image

### ISSUE THREAD

**Issue by PabloMontero** [11cafe/comfyui-workspace-manager#171]
Hello!

is it possible to remove these ugly icons when the thumbnail images have been unlinked?

<img width="345" alt="Screenshot 2024-02-01 at 17 07 19" src="https://github.com/11cafe/comfyui-workspace-manager/assets/22867200/1248c6ff-0fec-4673-8a74-43e283d8ae63">

Thank you!

**Comment by Weixuanf** [comment]
hi this should be fixed in the latest version, the broken thumbnails are automatically hided, once update, you shouldn't see this anymore, let me know if it doesn't work for you

**Comment by PabloMontero** [comment]
Awesome!!
