### ISSUE TITLE
Move Models Button to another place 

### ISSUE THREAD

**Issue by lakako** [11cafe/comfyui-workspace-manager#176]
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/46197434/06ec51d8-64dd-4521-ba5c-eb92c088d750)

Models Button will block settings button. Can we move models button to another place?

**Comment by Weixuanf** [comment]
<img width="134" alt="Screenshot 2024-02-03 at 5 33 53 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/180f4646-4211-4230-9729-4bd37d377a86">

will launch this move handle soon, so you can move it around

**Comment by DavidEBell** [comment]
> <img alt="Screenshot 2024-02-03 at 5 33 53 PM" width="134" src="https://private-user-images.githubusercontent.com/18367033/302026888-180f4646-4211-4230-9729-4bd37d377a86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5OTkwNjUsIm5iZiI6MTcwNjk5ODc2NSwicGF0aCI6Ii8xODM2NzAzMy8zMDIwMjY4ODgtMTgwZjQ2NDYtNDIxMS00MjMwLTk3MjktNGJkMzdkMzc3YTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDIyMTkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MDQ4NDA5MWYwMTRkOTlmZmE1OTVkMGE5MTU4MzA5ODBmMDk3NTZiZDdiZWRlMDc0MTZlZTY1MThmOTJmZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OdeFzs3TmZQg0vm_qEAsYMJiXmRCmCw-K30yc4kcNt0">
> will launch this move handle soon, so you can move it around

thank you.

**Comment by Weixuanf** [comment]
the new version is launched, you can update to see the handle and move this models button around!
