### ISSUE TITLE
I can't find the interface after updating comfyui.

### ISSUE THREAD

**Issue by whmc76** [11cafe/comfyui-workspace-manager#180]
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/129386342/6fc9aefa-b781-459c-bb7d-3779ba5d7627)

**Comment by Weixuanf** [comment]
can you `cd custom_nodes/comfyui-workspace-manager` and `git pull`? and restart your python server?

if that's not working, can you in your terminal in custom_nodes/comfyui-workspace-manage dir, can you `git checkout main` and restart server?

**Comment by whmc76** [comment]
let me try try... 
PS E:\IMAGE\ComfyUI_test\ComfyUI\custom_nodes\comfyui-workspace-manager> git pull
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
PS E:\IMAGE\ComfyUI_test\ComfyUI\custom_nodes\comfyui-workspace-manager> git checkout main
error: you need to resolve your current index first
dist/workspace_web/input.js: needs merge

**Comment by Weixuanf** [comment]
it seems you made some local changes to it...
you can `git reset --hard HEAD`

**Comment by Weixuanf** [comment]
if nothing is working, you can delete the comfyui-workspace-manager folder and reinstall, you should still have all your data

**Comment by whmc76** [comment]
fixed afer pull again
