### ISSUE TITLE
Load / update existing workspace from .json file

### ISSUE THREAD

**Issue by Vagabond999** [11cafe/comfyui-workspace-manager#183]
The issue with saving the workspaces in a separate file is if the .json file is changed outside the manager, the changes don't show and worse yet are overwritten once you select to the workspace.

My use case, I have a workstation with beefy gfx, and a laptop. I use ComfyUI on both, from the laptop. So 2 versions, one for editing and testing workflow edits, while running the remote box in another tab. 

I tried using a shared directory (dropbox & fileshare), but since the addon uses its own version of the workspace once its loaded, it's a mess to try to reload.

thought of a few ways this could be fixed
1) auto detect file versions, same as your detecting new files. (best way)
2) reload the workspace db from the .json files on page refresh
3) have an option to not use the db file and just load from the .json files when loading. This would prob lose some features, but file history on my box is saved elsewhere. 

Thanks! It's a few edits from being one of the most useful addons for ComfyUI !

**Comment by Weixuanf** [comment]
Hi thanks for the feedback! We need to enable two way sync to achieve this. Right now the local folder is a one way sync output folder.

it is on our plan to support it since we did get this request before more than once. I’ll update here once we have it!

**Comment by Weixuanf** [comment]
this is completed by our new two way sync in v2.0 please check it out
