### ISSUE TITLE
Error: Workflow not found!

### ISSUE THREAD

**Issue by tanzim5** [11cafe/comfyui-workspace-manager#187]
![302484949-680e6269-3639-4c91-ac15-eb692ea53935](https://github.com/11cafe/comfyui-workspace-manager/assets/13457096/a12d782c-7fa8-474c-9b8a-dbb00b12bda8)
It started couple of days ago. It keep showing me this error Error: Workflow not found!. Even when loading defaults. Anyone facing this issue?

**Comment by Weixuanf** [comment]
Oh that’s weird. Can you restart python server and go to 127.0.0.1 again see if it disappears. And can you still access the left side files drawer? If yes can you switch to a flow in the files drawer list?
