### ISSUE TITLE
couldn't automatically save the workflow

### ISSUE THREAD

**Issue by jinnaluo0** [11cafe/comfyui-workspace-manager#199]
Since I couldn't automatically save the workflow, I feel like I don't want to use this plugin anymore. It's only after frequent restarts that I realize that the process I've worked hard to adjust has been restored again

**Comment by Weixuanf** [comment]
what do you mean "I couldn't automatically save the workflow,"

have you enabled auto save in settings?
<img width="502" alt="298656239-061a8463-f7e6-4985-9516-8117d7a5edd5" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/b375023f-8264-4cb7-954a-0f3a789b5228">

You can also "Control + S" to save your workflow

**Comment by jinnaluo0** [comment]
thanks
