### ISSUE TITLE
If I use this plugin, I won't be able to use ctrl+c and ctrl+v in comfyui, what a pity!

### ISSUE THREAD

**Issue by shguxudong** [11cafe/comfyui-workspace-manager#20]
If I use this plugin, I won't be able to use ctrl+c and ctrl+v in comfyui, what a pity!

**Comment by Weixuanf** [comment]
Hi, please update the plugin to the newest version, this bug is fixed in the new version! 
Refresh, Restart browser to make sure the changes are included!
If you are still experiencing this bug, please let me know!

**Comment by shguxudong** [comment]
I have retrieved the latest version, but the problem still exists.
It seems that my CTRL+C cannot replicate any nodes now. And ctrl+v keeps pasting the same node, no matter how many times I use ctrl+c.   ;w;

**Comment by shguxudong** [comment]
Ctrl+x also failed

**Comment by shguxudong** [comment]
The problem has been resolved.
I deleted the entire plugin directory and reinstalled it to resolve the issue.
Thank you for your selfless contribution.
May the holy light shine upon you!

**Comment by Weixuanf** [comment]
Hahaha thank you for your appreciation! That's very humorous of you. Glad to know it's resolved! But I'm surprised that you have to reinstall to resolve it? So even you restarted server, restarted browser, it won't resolve it?
