### ISSUE TITLE
Prompt and other info not being saved in the gallery

### ISSUE THREAD

**Issue by fredlef** [11cafe/comfyui-workspace-manager#204]
For some workflows (see attached) prompt and other info not being captured in gallery.  I believe I am on 1.5.0 but the version.txt file reads 1.1.0 (verified that a fresh download of 1.5.0 shows 1.1.0).
[base_sdxl_with_LORA_emptylatent_w-text.json](https://github.com/gligen/GLIGEN/files/14336597/base_sdxl_with_LORA_emptylatent_w-text.json)

**Comment by Weixuanf** [comment]
hi thanks for the feedback. This is a known limitation now, the prompt info is limited to parsing the built-in ksampler node. We plan to upgrade this soon to be compatible with any custom nodes. Stay tuned!

**Comment by fredlef** [comment]
Thanks
