### ISSUE TITLE
不同机器数据不同步

### ISSUE THREAD

**Issue by zhuchen1109** [11cafe/comfyui-workspace-manager#208]
1.我在一台电脑更新了工作流A，在打开另一台电脑刷新页面，发现工作流A未能同步最新的，还是旧的
2.我在一台电脑用工作流A生成了图，在另一台电脑重新刷新，不能浏览到此图
想请问这二个问题有什么办法解决吗？做到同步

**Comment by Weixuanf** [comment]
你两台电脑是用的同一个ComfyUI的服务器吗？还是两台电脑各自从自己的硬盘里运行不同的ComfyUI的python server
________________________________
From: zhuchen ***@***.***>
Sent: Wednesday, February 21, 2024 4:46:19 PM
To: 11cafe/comfyui-workspace-manager ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [11cafe/comfyui-workspace-manager] 不同机器数据不同步 (Issue #208)


1.我在一台电脑更新了工作流A，在打开另一台电脑刷新页面，发现工作流A未能同步最新的，还是旧的
2.我在一台电脑用工作流A生成了图，在另一台电脑重新刷新，不能浏览到此图
想请问这二个问题有什么办法解决吗？做到同步

―

**Comment by zhuchen1109** [comment]
是启了一个comfui服务

**Comment by hay86** [comment]
我也碰到同样的问题，是db目前下folders.json在不同浏览器打开的时候被覆盖了，希望作者尽快fix

**Comment by Weixuanf** [comment]
噢噢好的 那这个都是因为我们还没有双向同步功能 目前只是从浏览器数据库到硬盘数据的单向同步

我会尽快实现双向同步功能

感谢建议
________________________________

**Comment by zhuchen1109** [comment]
给大佬点赞

**Comment by Laifang** [comment]
同样遇到这个问题，我开启了web服务端口的功能，在同一台电脑上，用不同的浏览器都会造成 工作流不同步的情况，会在comfyui根目录递归创建undefined/myworkflows 文件夹，如果开启了多用户功能更是混乱

**Comment by Weixuanf** [comment]
hi we have fixed it in beta branch. If you know git, could you checkout to beta branch and see if it works for you? **Before checkout to beta, please copy your comfyui/my_workflows/ folder to somewhere else as a backup**

hi beta branch里已经修复了这个问题，需要手动开启twoway sync，我们还在测试这个功能，如果你们会用git的话，能否checkout到beta branch 帮助我们测试一下？如果有问题欢迎及时反馈，这样也能帮我们尽快launch这个功能！在切换到beta分支前，请备份好你们的comfyui/my_workflows/ 文件夹，以免发生不测🫠

<img width="527" alt="Screenshot 2024-03-01 at 9 36 33 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/32c59308-b10a-470b-9a76-94ce925c4ff0">

**Comment by Laifang** [comment]
![捕获](https://github.com/11cafe/comfyui-workspace-manager/assets/20664974/096ead15-a8c6-42a7-8fcc-932adb2a266c)
您看看我这的文件夹有多混乱，我开启了多用户模式，就算是同一个用户开启不同浏览器浏览数据也是不一样的

**Comment by Laifang** [comment]
> 好的 感谢测试，我在修复这个bug
> 你可否试一下点击哪个铅笔的icon，然后直接写进去一个正常的windows的绝对路径

也是一样的 输入完了 看起来不会添加，但是一刷新就出现了

**Comment by Weixuanf** [comment]
Hi! Sorry for the delay. 

beta branch 已经更新啦 修复了windows上的所有问题，欢迎更新试用！希望收到反馈beta是否还有问题，可以帮助我们尽快launch beta！谢谢！
