### ISSUE TITLE
comfyui-workspace-manager is quite well！！！

### ISSUE THREAD

**Issue by vvip2u** [11cafe/comfyui-workspace-manager#210]
comfyui-workspace-manager is included in the git repo: 

https://github.com/vvip2u/ComfyUI-Classical-Nodes/tree/main

**Comment by Weixuanf** [comment]
wow thank you so much for the recognition! 😄 I like your summary of useful nodes and it's an honor for us to be included! 🥳

Feel free to suggest feedbacks and advices for us to improve better! 🍻 Cheers~
