### ISSUE TITLE
Drag and drop images change the name of the workflow

### ISSUE THREAD

**Issue by DmitryKripakov** [11cafe/comfyui-workspace-manager#213]
After recent updates, if you load an image into the Load Image node via Drag and Drop, the name of the workflow changes to the name of the loaded image. This is terribly inconvenient :)

If you upload an image through the "Choose File to Upload" button, there is no such problem.

https://github.com/11cafe/comfyui-workspace-manager/assets/33714232/f02b5e66-b897-4556-9f33-b30a7d78ff93

**Comment by Weixuanf** [comment]
hi this is now fixed, please update your comfyui and see if it works for you. Thank you very much for reporting this issue! this helps us improve the quality of our product 😊

**Comment by DmitryKripakov** [comment]
Everything works, the bug is gone! A very cool product, by the way, it helps a lot in my work, thank you very much! :)

**Comment by Weixuanf** [comment]
> Everything works, the bug is gone! A very cool product, by the way, it helps a lot in my work, thank you very much! :)

this is the best to hear for me that it helps in your work! 🥹🥳
