### ISSUE TITLE
部署在云服务器上面的ComfyUI显示不了这个插件

### ISSUE THREAD

**Issue by xiongaox** [11cafe/comfyui-workspace-manager#218]
<img width="1272" alt="image" src="https://github.com/11cafe/comfyui-workspace-manager/assets/40469438/70c0c83d-a0a9-4d52-ae4f-881184796de1">
<img width="1649" alt="image" src="https://github.com/11cafe/comfyui-workspace-manager/assets/40469438/550c551b-fc1e-41bb-9280-8075c00d4784">

**Comment by Weixuanf** [comment]
你好你用的什么云服务平台 Google colab还是什么 command terminal有任何报错吗 你的截图不完整我们没看到有workspace的报错，另外浏览器本身的console有任何报错吗（F12 or 右键inspect -> Console)

我在Google colab试了一下没有什么问题，可以加载
<img width="1219" alt="Screenshot 2024-02-26 at 8 10 08 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/3c16137d-b7fc-4a33-a1c0-3b840e84502e">

**Comment by Weixuanf** [comment]
我看这里有报错，没有加载出来我们的script：

<img width="791" alt="Screenshot 2024-02-28 at 8 07 33 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/bb82ce97-9017-4309-9c40-bf2c914b8a28">

你可以点击那个 workspace_web/input.js 的link，看看是为什么不能访问

你有重启过comfyui的python server吗 安装之后？

**Comment by xiongaox** [comment]
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/40469438/ee711581-6a7b-4d0e-9ee3-811a57339123)
点击之后，显示这个，这个是实例如果长时间不用，他会自动关闭的，这样算重启python server么

**Comment by Weixuanf** [comment]
重新运行是重启
看你的截图好像是没有权限 我也有点想不明白为啥 感觉可能这个环境运动的时候没权限之类的
________________________________

**Comment by songquanhe-gitstudy** [comment]
我遇到了同样的问题，也是使用的阿里云，请问有什么方式可以解决吗？

**Comment by xiongaox** [comment]
> 我遇到了同样的问题，也是使用的阿里云，请问有什么方式可以解决吗？

目前没有，作者也没找到什么原因

**Comment by songquanhe-gitstudy** [comment]
我修改了请求地址是ok，但是后面还有一系列问题。大概就是阿里代理增加了一些路径，而作者写的是绝对路径
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/15275582/fe10ae24-9fe9-4560-b645-235f46ada90e)

**Comment by xiongaox** [comment]
> 我修改了请求地址是ok，但是后面还有一系列问题。大概就是阿里代理增加了一些路径，而作者写的是绝对路径 ![image](https://private-user-images.githubusercontent.com/15275582/309176011-fe10ae24-9fe9-4560-b645-235f46ada90e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNzcwOTAsIm5iZiI6MTcwOTI3Njc5MCwicGF0aCI6Ii8xNTI3NTU4Mi8zMDkxNzYwMTEtZmUxMGFlMjQtOWZlOS00NTYwLWI2NDUtMjM1ZjQ2YWRhOTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA3MDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiM2YxMjc5ZjMzNzEwN2Q5N2NmZWY5MjAxNzc0MDc1YTg3N2MzNTg1ODExNTIwYjE5MzdmNWUyYmFjYTUyNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.luqkyFKp95kJTGvo7woIzdGg0qay_s6mj1AScqTq08c)

修改地址还有其他什么问题？可能没有全部修改干净？那得要作者大大看看了。

**Comment by Weixuanf** [comment]
> 我修改了请求地址是ok，但是后面还有一系列问题。大概就是阿里代理增加了一些路径，而作者写的是绝对路径 ![image](https://private-user-images.githubusercontent.com/15275582/309176011-fe10ae24-9fe9-4560-b645-235f46ada90e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNzc1NTksIm5iZiI6MTcwOTI3NzI1OSwicGF0aCI6Ii8xNTI3NTU4Mi8zMDkxNzYwMTEtZmUxMGFlMjQtOWZlOS00NTYwLWI2NDUtMjM1ZjQ2YWRhOTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA3MTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MmJiOTA4YzgxMzJjMTQwMjQ3MDczYTgyYjcxNGFmMmNkM2YyODYwNzBmMjYxYmMzZGJlMGQ1OWExMWRiZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jfD2Y1tMZqNUNWPXg3JtkIz5_6U59LJFtJtbew8VdDU)

谢谢你帮忙看代码哈！估计是改了地址之后vite打包出了问题，导致后续其他import错乱了。我回头看一下改一下vite.config里的一些东西我估计得

你们用的是这个云服务吗？
https://help.aliyun.com/zh/pai/user-guide/dsw-notebook-service/

**Comment by xiongaox** [comment]
> > 我修改了请求地址是ok，但是后面还有一系列问题。大概就是阿里代理增加了一些路径，而作者写的是绝对路径 ![image](https://private-user-images.githubusercontent.com/15275582/309176011-fe10ae24-9fe9-4560-b645-235f46ada90e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNzc1NTksIm5iZiI6MTcwOTI3NzI1OSwicGF0aCI6Ii8xNTI3NTU4Mi8zMDkxNzYwMTEtZmUxMGFlMjQtOWZlOS00NTYwLWI2NDUtMjM1ZjQ2YWRhOTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA3MTQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MmJiOTA4YzgxMzJjMTQwMjQ3MDczYTgyYjcxNGFmMmNkM2YyODYwNzBmMjYxYmMzZGJlMGQ1OWExMWRiZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jfD2Y1tMZqNUNWPXg3JtkIz5_6U59LJFtJtbew8VdDU)
> 
> 谢谢你帮忙看代码哈！估计是改了地址之后vite打包出了问题，导致后续其他import错乱了。我回头看一下改一下vite.config里的一些东西我估计得
> 
> 你们用的是这个云服务吗？ https://help.aliyun.com/zh/pai/user-guide/dsw-notebook-service/

是的，人工智能平台 PAI的DSW

**Comment by songquanhe-gitstudy** [comment]
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/15275582/4452159d-aaff-4116-a349-eb6f02707a6b)
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/15275582/f73ab5b3-1202-4225-8140-daf2a664090b)

后面的报错，你可以参考下，我没有太多时间来改这块 @Weixuanf

**Comment by Weixuanf** [comment]
> ![image](https://private-user-images.githubusercontent.com/15275582/309181575-4452159d-aaff-4116-a349-eb6f02707a6b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMTMyNDksIm5iZiI6MTcwOTMxMjk0OSwicGF0aCI6Ii8xNTI3NTU4Mi8zMDkxODE1NzUtNDQ1MjE1OWQtYWFmZi00MTE2LWEzNDktZWI2ZjAyNzA3YTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDE3MDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5ZjhhYmExY2Q1YzJjOTViMTFlNTk3NDRiMWRhMTM4MjA1YjNkZWY2Y2RmYTU4MjE5NzZhYWQ5NTdhY2Y1NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pBjW8VQOjSY6hz0IabS1ACeiCFtebW5nUMxPrYodTxo) ![image](https://private-user-images.githubusercontent.com/15275582/309181759-f73ab5b3-1202-4225-8140-daf2a664090b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMTMyNDksIm5iZiI6MTcwOTMxMjk0OSwicGF0aCI6Ii8xNTI3NTU4Mi8zMDkxODE3NTktZjczYWI1YjMtMTIwMi00MjI1LTgxNDAtZGFmMmE2NjQwOTBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDE3MDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2ZjA1NmM3NGVkN2I4MDRmMmQ1NTAwNmM0N2I4MjAxMzdmODA0YTFiMDcyOTA3MGVlZDNkMjU2NDUwNTQ3ZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lc2qYuzpLrfQiqL12ITZDMysmbewlKLoVlgL4Hu5Gps)
> 
> 后面的报错，你可以参考下，我没有太多时间来改这块 @Weixuanf

好的谢谢你哈 我回头看一下

**Comment by Weixuanf** [comment]
<img width="534" alt="Screenshot 2024-03-04 at 1 05 48 AM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/e832ce72-f550-43d7-81ce-63eb3ab2c574">

hi 你能否帮我截图一下 F12 inspect -> Source 里面的内容，尤其是 scripts/app.js. 以及 worksapce_web/ 里input.js 等内容的位置，我需要看一下这些文件存放的位置是什么

然后你右键点击 scripts/app.js 点击 “Open in new tab” (在新标签页中打开) 
<img width="345" alt="Screenshot 2024-03-04 at 1 09 02 AM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/415b2e99-e484-4a5e-aa11-2172516b4d21">

打开了scripts/app.js 的地址之后把他的地址copy给我一下
<img width="401" alt="Screenshot 2024-03-04 at 1 09 19 AM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/2dd0381d-b23d-48d9-bc02-1387d5efc3db">

同样的，右键点击 worksapce_web/input.js 复制地址或者新标签页打开复制地址

谢谢！！

**Comment by Weixuanf** [comment]
https://github.com/11cafe/comfyui-workspace-manager/commit/77d90eb0470a8081da716cc2a20987cf629d622f

我盲猜着修了一下。。。不知道修没修好 我明天部署一下阿里云测一下吧

**Comment by xiongaox** [comment]
卸载插件，重新安装后，依然不生效

scripts/app.js内容
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/40469438/5086f2b9-7935-40f1-bba1-6cfdec30d765)
和你不一样，没有 worksapce_web
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/40469438/40d5c799-862f-4564-9ff6-cac4120be3f4)

**Comment by Weixuanf** [comment]
能否给一个你用aliyun部署comfyui的notebook .pynb？我用了我在colab上用的notebook，不好使，cloudflare特别慢 hook不上。

**Comment by songquanhe-gitstudy** [comment]
你是否用的DWS，我可以给你一个镜像和notebook.pynb。v 17770086389

**Comment by Weixuanf** [comment]
after some debugging, this is due to we are using absolute import path for /scripts/app.js and  /scripts/api.js in our components:

```
// App.ts
import { app } from "/scripts/app.js";
import { api } from "/scripts/api.js";
```

this is troublesome since it will ignore the subpaths /proxy/8188 aliyun attached, and will look for resources at
`https://dsw-gateway-cn-shanghai.data.aliyun.com/dsw-3333/scripts/app.js`
while it is actually located at:
https://dsw-gateway-cn-shanghai.data.aliyun.com/dsw-3333/proxy/8188/scripts/app.js

we can't use relative path import like other plugins `../scripts/app.js`
because we are using vite to bundle our project, if we use relative path import, it will make vite to bundle app.js into its own bundle....

the only way to solve is to dynamic load all app.js and api.js in our source code, like
```
let app = null;
let api = null;

async function importModule(scriptName) {
  const basePath = window.location.pathname.split('/').slice(0, -1).join('/');
  const modulePath = `${basePath}/scripts/${scriptName}.js`;
  return import(modulePath);
}

async function loadModules() {
  const appModule = await importModule('app');
  app = appModule.app;

  const apiModule = await importModule('api');
  api = apiModule.api;
}

export { app, api, loadModules };
```

and we need to change every callsites of `import { app } from "/scripts/app.js";` and 
`import { api } from "/scripts/api.js";`

so a lot of changes...may not be able to fix this soon

**Comment by WangGosh** [comment]
I have also encountered this issue. If the author has resolved it, please declare it in this article

**Comment by Weixuanf** [comment]
> I have also encountered this issue. If the author has resolved it, please declare it in this article

hi这个问题一时半会儿不太好解决，需要大改代码，另一个遇到这个问题的朋友推荐了：https://cloud.megaease.cn/ 这个云服务，开箱即用，可以试试！谢谢！

**Comment by zhao-kun** [comment]
> > I have also encountered this issue. If the author has resolved it, please declare it in this article
> 
> hi这个问题一时半会儿不太好解决，需要大改代码，另一个遇到这个问题的朋友推荐了：https://cloud.megaease.cn/ 这个云服务，开箱即用，可以试试！谢谢！

We have provided a out of box service to use the Stable Diffusion ComfyUI, the plugin worked very well in the service.

**Comment by TheBloodthirster** [comment]
@Weixuanf  同样阿里云dsw 转发出现问题，端口转发错误启动不了

**Comment by Weixuanf** [comment]
> @Weixuanf 同样阿里云dsw 转发出现问题，端口转发错误启动不了

嗯 我过两天修一下

**Comment by TheBloodthirster** [comment]
> > @Weixuanf 同样阿里云dsw 转发出现问题，端口转发错误启动不了
> 
> 嗯 我过两天修一下

搞了个域名挂载替代127.0.0.1:8188地址就可以了，也是无语阿里云瞎搞多了一层workspace_web的层级搞得一大堆插件都挂了
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/16109867/9dd4f0fe-9a17-49ce-b7f7-34859eaaeed2)
不过还是有个反推插件挂了：/extensions/pysssss/WD14Tagger/wd14tagger.js TypeError: Failed to fetch dynamically imported module:

**Comment by Jhonwivk** [comment]
> > > @Weixuanf 同样阿里云dsw 转发出现问题，端口转发错误启动不了
> > 
> > 
> > 嗯 我过两天修一下
> 
> 搞了个域名挂载替代127.0.0.1:8188地址就可以了，也是无语阿里云瞎搞多了一层workspace_web的层级搞得一大堆插件都挂了 ![image](https://private-user-images.githubusercontent.com/16109867/325685833-9dd4f0fe-9a17-49ce-b7f7-34859eaaeed2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MjUwOTUsIm5iZiI6MTcxNTUyNDc5NSwicGF0aCI6Ii8xNjEwOTg2Ny8zMjU2ODU4MzMtOWRkNGYwZmUtOWExNy00OWNlLWI3ZjctMzQ4NTllYWFlZWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE0Mzk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNTJkM2NjNjVmYjhlYWJiMWU0ZmY5Y2FkMmUwYTk4Y2E3YTIyODE0NzEzMGEwMzc0YjhlYTIyYjUxMmZkMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xxDfRA7g_8qAWT5KN4wjxS3m4BWz_1sCGHhosYbiGGQ) 不过还是有个反推插件挂了：/extensions/pysssss/WD14Tagger/wd14tagger.js TypeError: Failed to fetch dynamically imported module:

除了这种域名挂载的方式，还有什么解决办法吗，没有workspace manager好烦

**Comment by TonyDua** [comment]
> :



> > > @Weixuanf 同样阿里云dsw 转发出现问题，端口转发错误启动不了
> > 
> > 
> > 嗯 我过两天修一下
> 
> 搞了个域名挂载替代127.0.0.1:8188地址就可以了，也是无语阿里云瞎搞多了一层workspace_web的层级搞得一大堆插件都挂了 ![image](https://private-user-images.githubusercontent.com/16109867/325685833-9dd4f0fe-9a17-49ce-b7f7-34859eaaeed2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MDQwMDQsIm5iZiI6MTcxNTgwMzcwNCwicGF0aCI6Ii8xNjEwOTg2Ny8zMjU2ODU4MzMtOWRkNGYwZmUtOWExNy00OWNlLWI3ZjctMzQ4NTllYWFlZWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDIwMDgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNjg5ODM1ZTkxMmVlM2FiYWJmZjY5MDc1OTYxYjY5YTk4MGJiOWMwOGQ3Y2RmYjgwZmY2ZDU5MDFiZGMyMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AV022Wu9eOrtBDcGpbpC1XMdrHGHIAKumJEaf0KXxv4) 不过还是有个反推插件挂了：/extensions/pysssss/WD14Tagger/wd14tagger.js TypeError: Failed to fetch dynamically imported module:

@TheBloodthirster 请问大佬怎么挂载的域名（不小心点开了一个信的issue，sorry）

**Comment by TheBloodthirster** [comment]
> > :
> 
> > > > @Weixuanf 同样阿里云dsw 转发出现问题，端口转发错误启动不了
> > > 
> > > 
> > > 嗯 我过两天修一下
> > 
> > 
> > 搞了个域名挂载替代127.0.0.1:8188地址就可以了，也是无语阿里云瞎搞多了一层workspace_web的层级搞得一大堆插件都挂了 ![image](https://private-user-images.githubusercontent.com/16109867/325685833-9dd4f0fe-9a17-49ce-b7f7-34859eaaeed2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MDQwMDQsIm5iZiI6MTcxNTgwMzcwNCwicGF0aCI6Ii8xNjEwOTg2Ny8zMjU2ODU4MzMtOWRkNGYwZmUtOWExNy00OWNlLWI3ZjctMzQ4NTllYWFlZWQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDIwMDgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNjg5ODM1ZTkxMmVlM2FiYWJmZjY5MDc1OTYxYjY5YTk4MGJiOWMwOGQ3Y2RmYjgwZmY2ZDU5MDFiZGMyMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AV022Wu9eOrtBDcGpbpC1XMdrHGHIAKumJEaf0KXxv4) 不过还是有个反推插件挂了：/extensions/pysssss/WD14Tagger/wd14tagger.js TypeError: Failed to fetch dynamically imported module:
> 
> @TheBloodthirster 请问大佬怎么挂载的域名（不小心点开了一个信的issue，sorry）

我这边是走公司内部注册的域名方式，可能对外不具有通用性。
但是思考方式可以分享一下：之前遇到过一些nginx反向代理对于一些通用的服务无法百分百覆盖，特别是会带子目录的场景，
阿里云的转发启动路径路径相当于就是这台机器的路由，把这个开发机挂一个vip-server，然后搞个域名挂上去就行了
启动的时候要设置ip为0.0.0.0，而不是127.0.0.1或者localhost
https://help.aliyun.com/zh/lh/user-guide/domain-name-registration-icp-filing-and-resolution

**Comment by Weixuanf** [comment]
hi 我修了一下这个问题，在最新版本，麻烦实用一下，希望能解决这个问题～谢谢！
