### ISSUE TITLE
Top bar issue

### ISSUE THREAD

**Issue by Dachiko** [11cafe/comfyui-workspace-manager#22]
Right now the entire top row of the window occupied by workspace manager, which makes it impossible to interact with the workspace itself in that top region of the screen.
Could you please limit the space used by the workspace manager to the leftmost space where all the controls are?

**Comment by Weixuanf** [comment]
OK i'll limit it to only the top left section of the screen, will that work for you?

**Comment by Weixuanf** [comment]
hi this issue is fixed in the new version. Workspace manager now only occupies the top left corner and doesn't span the entire top region. If you pull the latest updates you should see it fix. Let me know if this solves your problem.
