### ISSUE TITLE
【Bug】Something wrong with the working directory

### ISSUE THREAD

**Issue by vvip2u** [11cafe/comfyui-workspace-manager#221]
> 工作目录有问题，不知道为什么会去到undefined目录下。
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/20998070/95dcdb74-5626-491d-8fa0-b8fb01ade094)

> 另外的情况变成了嵌套
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/20998070/3eedb19b-39aa-4c98-a352-55cb0bbf0ca2)

所以

1 - 能不能设定一个绝对目录用来存储
2 - 用户能不能自行设定一个目录用来存储，方便后续打包什么的

**Comment by Weixuanf** [comment]
<img width="541" alt="Screenshot 2024-02-27 at 8 51 34 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/0d95ef4b-733a-4f9a-8c67-dd4136677ba3">

你检查一下你settings里的这个地方 是不是目录的名称有问题，可以点击旁边的按钮更改 或输入绝对目录

**Comment by vvip2u** [comment]
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/20998070/bf8e4cd3-9abe-43c0-a6fe-8e30da6fff4a)
这里面是这样的

**Comment by Weixuanf** [comment]
<img width="423" alt="Screenshot 2024-02-28 at 4 18 25 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/97abdd52-f7f9-4a45-a464-2af5a5e13637">

你重新选一下路径？看看有没有用 你是不是有段时间没更新workspace manager插件的版本了？

**Comment by Laifang** [comment]
开发者用的是mac电脑啊，和windows的肯定有区别

**Comment by Weixuanf** [comment]
这个在最新版本已经修复
