### ISSUE TITLE
修改了extra_model_paths.yaml配置路径的模型，无法在models按钮里显示。

### ISSUE THREAD

**Issue by yangyiyu11** [11cafe/comfyui-workspace-manager#224]
作者好：
我使用comfyui在extra_model_paths.yaml修改了和webui共享模型，原始模型文件在webui的文件夹中。使用此工具在models面板中没有模型显示，但实际上我安装了很多模型。_如下图：_
<img width="453" alt="f15263f79dc7e3fecae2c95a598bd8a8" src="https://github.com/11cafe/comfyui-workspace-manager/assets/8320313/7572ee57-02e5-4ff2-aea3-bc6a87cd4bc0">

请您查看，是否存在我不清楚的使用或设置方法，还是此工具目前还不支持此功能。
感谢您。

**Comment by Weixuanf** [comment]
hi the new version 2.0 will soon fix this problem. Will launch it in a few days.

hi新版本2.0马上就回修复这个问题，过几天就会launch～感谢支持

**Comment by Weixuanf** [comment]
hi beta branch已经修复了这个问题，欢迎更新到beta试用！
https://github.com/11cafe/comfyui-workspace-manager?tab=readme-ov-file#beta-preview

期待您的反馈！可以帮助我们尽快launch beta 😊

**Comment by Bracelee81** [comment]
git clone升级后还是老样子，旧点的版本好像还没问题
