### ISSUE TITLE
[Lock Workflow feature request] A simple request for saving

### ISSUE THREAD

**Issue by APCOTech** [11cafe/comfyui-workspace-manager#232]
Hi, thank you so much for the great workflow organizer, it is very useful. but I just have a simple request and I hope yo u would consider it:

A simple workspace operation:
I mainly have 10 or 12 main workflows that I use most of the time for generating, inpainting, outpainting, SVD... etc.

But I want them FIXED. I do not want to be prompted to save or overwrite them. I switch between them a lot, and the saving warning is a little bit annoying every time. so, as you added a check box to disable auto saving, can you please provide a checkbox to disable the saving completely? I know it sounds crazy, but trust me, many people do not want their original workflows to be overwritten with changed values in the nodes. Since I already can save them with the (save workflow) when I need to save a better version of the workflow.

Thank you,

**Comment by Weixuanf** [comment]
Thanks for the suggestion. I think we’ve got this request before. So you’re not the only one want this, definitely not crazy haha

so I’m thinking to add a “Lock Workflow” option in the Files dropdown menu. If you click lock workflow, that workflow can not be modified or changed anymore, unless you click “Unlock Workflow “

do you think this will solve your problem?

**Comment by APCOTech** [comment]
Of course, that will be a perfect solution for me. This way I can lock my main workflows. Thank you a lot in advance

**Comment by Weixuanf** [comment]
<img width="557" alt="Screenshot 2024-03-11 at 12 48 07 AM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/96871e3d-6d9e-4bea-8f90-071fae548380">

the lock workflow feature is done, please use this button to switch ^^

**Comment by APCOTech** [comment]
Life saver <3
Thank you a lot for the great work. it works perfect as intended and as needed.
