### ISSUE TITLE
[Bug] Sometimes text disappears for no reason

### ISSUE THREAD

**Issue by LukeG89** [11cafe/comfyui-workspace-manager#245]
Hi, I really enjoy using your workspace manager! Thanks for creating it!

Just wanted to report a strange issue that I've been experiencing for quite a lot.
Sometimes, when I open a workflow, the text inside one or more nodes (for example prompts but also other text boxes) has disappeared.

If I click "Discard unsaved changes" all the missing text magically reappears. 

I don't know what is causing that, it is quite random and I can't figure out why. 

What could be the cause? Am I the only one having this issue?

**Comment by Weixuanf** [comment]
"CLIP Text Encode" nodes? Do you mean the entire node disappears or just the text content becomes empty inside the node?

Umm that's a bit weird..

**Comment by LukeG89** [comment]
> "CLIP Text Encode" nodes?

Yes, most of the time it's either the positive or the negative one that disappears (I can't remember if both prompts has ever disappeared at the same time).

> or just the text content becomes empty inside the node?

Yes, just the text content.

Once has also happened to other text boxes inside "clipseg" and "segment anything" nodes.

**Comment by Weixuanf** [comment]
> If I click "Discard unsaved changes" all the missing text magically reappears.

this means the last time you saved it, it got the text. But somehow the text value was cleared after you last saved...🤔it's def very strange if you haven't manual cleared any text content.

I'd suggest use the Versions History -> Change history to monitor changes and you can also bring back earlier changes

**Comment by LukeG89** [comment]
> Do you have auto save enabled?

Yes, could it be the cause? Now I'll try turning off autosave mode and see.

> I can't think of why this would happen, very strange..

I know, it's also hard to figure out because it doesn't happen really often.

Maybe Two-way sync will fix the problem by itself? (when you release 2.0 I mean)

> I'd suggest use the Versions History -> Change history to monitor changes

About Version History: Where are all versions stored? Inside browser?

**Comment by LukeG89** [comment]
### UPDATE

I've tried disabling your custom node and it was happening anyway!

Then I found out that `pythongosssss/ComfyUI-Custom-Scripts` is the real cause of the issue! 

After some testing, I see that after you click "Clear" and then open another workflow, one text disappears.

Here is an example:

https://github.com/11cafe/comfyui-workspace-manager/assets/161304036/ccd60f35-9d75-4447-be70-8738ea4761e4

This doesn't happen when disabling Custom-Scripts. 

Sorry for the inconvenience!

**Comment by Weixuanf** [comment]
Oh I see, thanks for letting me know! 

> After some testing, I see that after you click "Clear" and then open another workflow, one text disappears.

oh gotcha this is a weird bug. I also have custom scripts installed myself, I didn't notice this before, so I just tried your routine too, create workflow1 with text, then workflow2 then clear, then switch to workflow1, I still see the text there 🤔 I'm using MacOS + chrome though.

But I'm glad that you figured out the problem, it's difficult to find out.

**Comment by LukeG89** [comment]
> I still see the text there 🤔 I'm using MacOS + chrome though.

It could be Windows or probably there is a conflict between Custom Scripts and another custom node... But I have something like 50 nodes installed... I think I will keep the bug and enjoy life :)

Thank you for trying helping me out! Have a good day!

**Comment by Weixuanf** [comment]
*

I think I will keep the bug and enjoy life :)

Haha that’s the spirit. Np, thanks for using our plugin 😊😊

________________________________
