### ISSUE TITLE
It is already the latest version, but it has the following errors

### ISSUE THREAD

**Issue by xavierzz** [11cafe/comfyui-workspace-manager#248]
Loading: Workspace Manager (V1.0.0)
[03/07/24 14:59:04] WARNING  Your inference package version      __init__.py:35
                             0.9.13 is out of date! Please
                             upgrade to version 0.9.15 of
                             inference for the latest features
                             and bug fixes by running `pip
                             install --upgrade inference`.

**Comment by Weixuanf** [comment]
ummm weird,  I don't think this is related to our package, we don't have version check and we don't use inference pip package
