### ISSUE TITLE
All workflows missing after update

### ISSUE THREAD

**Issue by sacredbone** [11cafe/comfyui-workspace-manager#259]
Okay, first a little feedback: 
This is now the third time all workflows are missing, and I think after multiple problems **_I am now at a stage where I consider not using this extension anymore_**. I think it is the way this extension is handling the files/workflows which doesn't fit to a lot of use cases from comfyUI (i.e. using multiple workflows at the same time, and using multiple browsers etc) - at least not for me. In my personal opinion it should not use the browser storage (or a db) and focus more on data consistency, I would rather have less functionality but a working reliable tool instead.

**But anyway, I want to describe the issue so that it can be fixed:**
After updating to the newest version after restarting comfyUI, it opens comfyUI without the extensio visible. If I reload an existing workflow, all saved workflows are gone.

1. First time this happens I used Brave browser and I needed to clean the whole browser storage and everything to make the extension show up again. At the time I didn't have much workflows imported - so I didn't notice the some workflows were not showing up.
2. Second time the same behavior, using Brave browser - extension not showing up after update, after cleaning the storage all workflows are gone. So I switched to my Chrome browser, where the workflows were still in the list.
3. Now the third time I got the same problem in Chrome browser, but this time extension is showing up - but only show the folders - no workflows.

Both Google Chrome and Brave browser are always up to date (Chrome is Version 122.0.6261.112 atm)

This is the console output - let me know if you need more info
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/107143108/bae03c27-d485-491e-bb96-afd158743eb2)

**Comment by Weixuanf** [comment]
i'm really sorry for the inconvenience.

1. Do you still have your ComfyUI/my_workflows folder? Do you still have your .json backups there?

2. we have upgraded to v2.0
https://github.com/11cafe/comfyui-workspace-manager?tab=readme-ov-file#v20-beta-two-way-sync-with-local-folder-select-model-install-path-cloud-sync-workflows

in v2.0, we will directly store all your workflow .json in your disk, by default under `ComfyUI/my_workflows`, so even if you change browser, you will still see the same workflow files. And if you put any .json files inside `ComfyUI/my_workflows` using your File Explorer, they will automatically show up in workspace's UI. **You just need to keep your ComfyUI/my_workflows folder safe and backup it once in a while**

The browser storage will only be used to store metadata info like versions, gallery images.

We will be further migrating away from browser storage completely, and will store all metadata info in your local disk too, inside `ComfyUI`, (using SQLite). 

Please upgrade to v2.0 and let me know if it works for you! Let me know if you have any questions or issues. Thank you for reporting this issue.

**Comment by sacredbone** [comment]
> 1. Do you still have your ComfyUI/my_workflows folder? Do you still have your .json backups there?

Yes, they are - I also created a backup before the update

> 2. we have upgraded to v2.0
>    https://github.com/11cafe/comfyui-workspace-manager?tab=readme-ov-file#v20-beta-two-way-sync-with-local-folder-select-model-install-path-cloud-sync-workflows
> 
> in v2.0, we will directly store all your workflow .json in your disk, by default under `ComfyUI/my_workflows`, so even if you change browser, you will still see the same workflow files. And if you put any .json files inside `ComfyUI/my_workflows` using your File Explorer, they will automatically show up in workspace's UI. **You just need to keep your ComfyUI/my_workflows folder safe and backup it once in a while**

That sounds like a huge step forward.

> The browser storage will only be used to store metadata info like versions, gallery images.
> We will be further migrating away from browser storage completely, and will store all metadata info in your local disk too, inside `ComfyUI`, (using SQLite). We also realized that browser storage is not a good design decision 🙁.

Sometimes it's just like that, unfortunately, but I would like to emphasise that I really like the extension. The UI and the concept are both really good. But stepping away from browser storage is for sure a good descision.

> Please upgrade to v2.0 and let me know if it works for you! Let me know if you have any questions or issues.

will do :)

**Comment by Weixuanf** [comment]
> Yes, they are - I also created a backup before the update

That's great! It's definitely good idea to backup your /my_workflows folder once in a while, even after switched to 2.0, just in case

> Sometimes it's just like that, unfortunately, but I would like to emphasise that I really like the extension. The UI and the concept are both really good. But stepping away from browser storage is for sure a good decision.

thank you very much for your support. We hope we can make it better, so your constructive feedbacks are very important for us! please help us improve. 😊
