### ISSUE TITLE
All of my workflows are missing connections only when dragging them in.

### ISSUE THREAD

**Issue by Jellybit** [11cafe/comfyui-workspace-manager#267]
This issue has occurred since 2 updates ago (not only the most recent one, but the one before that). Whenever I drag in a workflow, all of the connections are missing. If I load the workflow alone, it still has the connections. I've attached an example.

[Random Aspect Ratio.json](https://github.com/11cafe/comfyui-workspace-manager/files/14560707/Random.Aspect.Ratio.json)

This may not happen on all workflows, but it happens on all the modular pieces I've made, for whatever reason. If I copy from this json, then paste into another workflow, it works fine. Only drag and drop breaks it.

**Comment by Tobe2d** [comment]
I have a similar issue... many of my workflows become the default workflow, and I lose all the hard work I put into creating them.

I really hope they will find a solution for this ASAP.

**Comment by Weixuanf** [comment]
> many of my workflows become the default workflow, and I lose all the hard work I put into creating them.

Sorry could you explain a bit more how drag and drop made your workflows disappear to default workflow? If you drag and drop workflowA to the the canvas which is currently showing workflowB then it made your workflowB become default workflow? 😨how did it happen?

Can you control+z to revert back, or can you go to "versions history" to find previous saved versions of your workflow?


________________________________

**Comment by Jellybit** [comment]
To be clear, I'm very certain this "default workflow" issue is not the same as mine. On mine, the workflow drags in okay, except all the connections between nodes are lost.

**Comment by Weixuanf** [comment]
Hi are you in the latest version? I latest we fixed some issues about dragging
I tried to download your Random Aspect Ratio.json<https://github.com/11cafe/comfyui-workspace-manager/files/14560707/Random.Aspect.Ratio.json> workflow and I ran on my Mac + chrome browser. Dragging it into another workflow seems fine with all links

Can you help me check F12 a> console and see if there's warning or error?

Thank you!
________________________________

**Comment by SakanakoChan** [comment]
same here, im on windows 11 and my comfyUI version is commit 2a813c3b. When i dragged my workflow from this extension, all the connections are lost. This issue seems to happen in all of my workflows.

**Comment by Steudio** [comment]
> same here, im on windows 11 and my comfyUI version is commit 2a813c3b. When i dragged my workflow from this extension, all the connections were lost. This issue seems to happen in all of my workflows.

I have the same problem, "Dragged and dropped sub-workflows into current workflow only show nodes no links
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/159500950/b0be7a09-7776-4d68-ba1b-cecb81c83579)

**Comment by Weixuanf** [comment]
hi i have debugged for many hours but can't find a perfectly solution for drag and drop...I have updated it in the README in home page calling for help. Maybe I'll also post the question into the ComfyUI dev chats community to get help. Sorry for the inconvenience.

**Comment by Weixuanf** [comment]
this is the code if anyone is interested:
https://github.com/11cafe/comfyui-workspace-manager/blob/d2d2f0c1f1ace35236e73fa5074e9feb83342773/ui/src/utils.tsx#L192

related: https://github.com/11cafe/comfyui-workspace-manager/issues/272
