### ISSUE TITLE
Typing after drag and drop

### ISSUE THREAD

**Issue by EdKZoo** [11cafe/comfyui-workspace-manager#272]
When i drag and drop any workflow with a text box in it, i cannot type in any textboxes from that point onwards. The textbox disapears after i start typing the first letter.

**Comment by Weixuanf** [comment]
thanks for reporting.. i have debugged for the entire afternoon and could not find a working solution 😢
If you try to refresh after you drag drop, it may work again. But I have tried everything can't find a better solution now. 😿

**Comment by EdKZoo** [comment]
i don't know if that helps, but i get this error in the console:
litegraph.core.js:5641 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
LGraphCanvas.bindEvents @ litegraph.core.js:5641
LGraphCanvas.setCanvas @ litegraph.core.js:5599
LGraphCanvas @ litegraph.core.js:5355
Fp @ App-to8jIIgG.js:7
O @ RecentFilesDrawer-N-0iIOB7.js:8


Also, i found a way to somehow fix it. You press f12>go to Elements Tab>Event Listeners>keyup>(refresh), then you remove the keyup "document" event listener, it will fix the problem. I wish i could help more but i don't know how to code.

**Comment by Weixuanf** [comment]
> i don't know if that helps, but i get this error in the console: litegraph.core.js:5641 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952 LGraphCanvas.bindEvents @ litegraph.core.js:5641 LGraphCanvas.setCanvas @ litegraph.core.js:5599 LGraphCanvas @ litegraph.core.js:5355 Fp @ App-to8jIIgG.js:7 O @ RecentFilesDrawer-N-0iIOB7.js:8
> 
> Also, i found a way to somehow fix it. You press f12>go to Elements Tab>Event Listeners>keyup>(refresh), then you remove the keyup "document" event listener, it will fix the problem. I wish i could help more but i don't know how to code.

Thank you so much for trying to help!! Thanks to @longgui0318  this should be fixed now, please update to latest version and see if it's working :)

**Comment by EdKZoo** [comment]
Thank you very much! keep up with the good work!
