### ISSUE TITLE
model图片格式问题导致无法正常在model管理菜单显示已有模型

### ISSUE THREAD

**Issue by Laifang** [11cafe/comfyui-workspace-manager#273]
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/20664974/ff06f634-eeec-4fa7-9c61-790fdbd36367)
希望做好好异常处理，读取出错也可以跳过啊，不要导致其他的模型无法显示

**Comment by Weixuanf** [comment]
hi感谢report，最新版本的修复了这个问题，加了try catch了～可以更新看看

**Comment by Laifang** [comment]
> hi感谢report，最新版本的修复了这个问题，加了try catch了～可以更新看看

指的是beta版本吗
