### ISSUE TITLE
Files All Missed

### ISSUE THREAD

**Issue by Vontean** [11cafe/comfyui-workspace-manager#276]
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/65079079/cc087f46-c572-4e8e-8ff3-178136e85224)
今天重启后，workspace中的文件都消失了，我没有其他备份，我该怎么办？

**Comment by Weixuanf** [comment]
Comfyui/my_workflows 文件夹里里有备份吗？你换浏览器了吗 你是本地还是云端gpu运行
________________________________
From: Vontean ***@***.***>
Sent: Friday, March 15, 2024 12:24:09 PM
To: 11cafe/comfyui-workspace-manager ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [11cafe/comfyui-workspace-manager] Files All Missed (Issue #276)


image.png (view on web)<https://github.com/11cafe/comfyui-workspace-manager/assets/65079079/cc087f46-c572-4e8e-8ff3-178136e85224>
今天重启后，workspace中的文件都消失了，我没有其他备份，我该怎么办？

―

**Comment by Weixuanf** [comment]
comfyui-workspace-manager/db 里还有workflows.json 文件吗
________________________________

**Comment by Vontean** [comment]
本地运行，Comfyui/my_workflows 只剩下三个古早的json了。不知道是不是edge从dev版本降下来的原因？
（没事，我已经用生成图，收回来重要的workflow了）

**Comment by Weixuanf** [comment]
你F12，我看一下console log 有没有报错

>不知道是不是edge从dev版本降下来的原因？
什么意思 你之前切换到workspace- manager的dev分支过？

comfyui-workspace-manager/db 文件夹里 workflows.json 这个文件还有吗 这个有的话也还可以恢复

另外你应该还在旧版本 可以之后更新到最新版，会双向同步直接从硬盘读写workflow json 不会再存在browser storage里面了 更稳定一些
________________________________

**Comment by Vontean** [comment]
我已经更新了最新版，comfyui-workspace-manager/db中的workflow.json文件在，但已经被新修改过了hhh。应该是我的edge浏览器重装导致的错误。总之workflow有找回，谢谢你的帮助！

**Comment by Weixuanf** [comment]
好的。感觉没帮上什么。 你以后偶尔backup一下ComfyUI/my_workflows/ 文件夹 以免出什么问题
________________________________
