### ISSUE TITLE
 [Feature request] Disable Auto-save dragged image.

### ISSUE THREAD

**Issue by enternalsaga** [11cafe/comfyui-workspace-manager#284]
My habit includes drag and drog several images to check their workflows and each time the node adds them to workflow folder that was very fustrated to delete them after. Please add a feature to turn auto-save off when needed.
Thank you.

**Comment by Weixuanf** [comment]
<img width="461" alt="Screenshot 2024-03-16 at 1 44 19 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/dc82ada8-55ad-4c7d-9df1-c1f35bc00236">

Hi turn on this setting in Settings modal, and it will not create new workflow when you drag an image to canvas, it will overwrite current workflow instead. but make sure you are aware that it will OVERWRITE the current workflow each time you drop a file on canvas, and make sure you have your changes saved somewhere.

**Comment by kryfo** [comment]
> <img alt="Screenshot 2024-03-16 at 1 44 19 PM" width="461" src="https://private-user-images.githubusercontent.com/18367033/313376729-dc82ada8-55ad-4c7d-9df1-c1f35bc00236.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MzczMTcsIm5iZiI6MTcxMTkzNzAxNywicGF0aCI6Ii8xODM2NzAzMy8zMTMzNzY3MjktZGM4MmFkYTgtNTVhZC00YzdkLTlkZjEtYzFmMzViYzAwMjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDAyMDMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMzFjZGM4NWJhYjY3ZTI4NDljYTZmYzk2YTc3NWRhMzVjYmJjMzAwZTI1YzM1ZjYyNzA5MWYyYjRlNDQwOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P4d4yiDG_XUhAwqdPRC_CcLirfaO4r7nP8jMj7ox3DA">
> Hi turn on this setting in Settings modal, and it will not create new workflow when you drag an image to canvas, it will overwrite current workflow instead. but make sure you are aware that it will OVERWRITE the current workflow each time you drop a file on canvas, and make sure you have your changes saved somewhere.

But it will automatically save my original workflow. This kind of random change of files is very annoying.

**Comment by Weixuanf** [comment]
this should be already fixed in the latest version, just make sure you disabled auto save mode and use manual save mode.
