### ISSUE TITLE
A couple of simple requests: Remove thumbnail and color matching

### ISSUE THREAD

**Issue by LukeG89** [11cafe/comfyui-workspace-manager#285]
Hi, just wanted to report two little things: an issue with thumbnails and a color mismatching.

Even after removing all images inside Gallery, the thumbnail doesn't disappear as usual:

https://github.com/11cafe/comfyui-workspace-manager/assets/161304036/b1bd1865-11c9-4d38-a3d2-da0684a3bb71

Would it be possible to remove it?
And also, would it be possible to stop creating images inside gallery?

My second request is about color matching. **Models** and **File** buttons kinda clash together, especially now that they are next to each other.
 
![current_colors](https://github.com/11cafe/comfyui-workspace-manager/assets/161304036/1b5733d2-4073-40a6-8aa8-331d24797a74) 

Would it be possible to change the **Models** color to better blend in the topbar? 

I don't know, for example something like that:
![color_matching](https://github.com/11cafe/comfyui-workspace-manager/assets/161304036/96f92b0d-65bb-4c29-a9a8-fc8bd13262f6)

**Comment by Weixuanf** [comment]
>And also, would it be possible to stop creating images inside gallery?

I have this on roadmap but haven't got time to implement yet, geez so busy sorry 🫠. I plan to add a checkbox in settings, that you can enable/disable creating images in gallery.
https://github.com/orgs/11cafe/projects/1/views/1?pane=issue&itemId=53941940

>Would it be possible to remove it?
simplest you can do is to rename the image inside your ComfyUI/outputs folder, that way, it can't be recognized by the gallery.

About the button colors, yeah i can see how it looks changing the colors, actually i have been experimenting with different colors, sometimes I feel the green is a bit too glaring hehe

thanks for these suggestions.

**Comment by LukeG89** [comment]
> I have this on roadmap but haven't got time to implement yet, geez so busy sorry 🫠. I plan to add a checkbox in settings, that you can enable/disable creating images in gallery.

Great! 😄 

> I wonder why you don't like adding images in gallery? Is there something you don't like about the gallery feature?

To be honest, I have two main reasons:

First, I can't find it useful since I have already saved all the images. If I want to load a workflow, I just drag and drop the image from my local folder. Also, when you remove the images from output, it's just a graveyard of broken thumbnails
![broken_thumbnails](https://github.com/11cafe/comfyui-workspace-manager/assets/161304036/9d7184ef-7a8a-4730-a569-68fa4e7c9e96)

Second, it's kinda uncomfortable when creating NSFW images. Do I have to explain myself? 😅 

In general I would prefer not having images/thumbnails in my workflows. If I want, now I can set a custom thumbnail thanks to your recent update!

Is there something I am missing about the usefulness of the gallery?

> About the button colors, yeah i can try to match the colors, actually i have been experimenting with different colors, sometimes I feel the green is a bit too glaring hehe. Thanks for the cool mockup

I can understand. To be honest again, I really liked the "minimal" style as it was many updates before (no colors at all). I would suggest to stick with that style, minimal is always the best choice.

**Comment by Weixuanf** [comment]
wow thanks very much for the sincere feedbacks about gallery, this is very useful for us!

>  graveyard of broken thumbnails

yeah we should def improve this, in future, it should automatically remove images thats are broken.

In future, gallery will be more like a way to inspect your image metadata, like prompts, models, cfg used, etc. Also, as a webUI to tune parameters of your built workflows, like this:

![313106841-0adde975-2de5-4283-9b73-d549b8d3a249](https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/bd41a9f9-c084-4923-8b58-54a43c325359)

But we're still implementing this functionality. 

But surely, we should still add the option in settings to disable adding images to gallery 😊

**Comment by LukeG89** [comment]
> In future, gallery will be more like a way to inspect your image metadata, like prompts, models, cfg used, etc. Also, as a webUI to tune parameters of your built workflows, so that you can easily build a customized UI for.your workflow

That seems a really cool feature! 😄 

> But surely, we should still add the option in settings to disable adding images to gallery 😊

It would be great, too! Keep up the good work! 🔥
