### ISSUE TITLE
"Upgrade to 2.0 - enable two way sync" window always pops up

### ISSUE THREAD

**Issue by ManOrMonster** [11cafe/comfyui-workspace-manager#288]
After updating a few days ago, this window keeps popping up, even though two way sync is already enabled:

<img width="429" alt="image" src="https://github.com/11cafe/comfyui-workspace-manager/assets/3925151/0f1eeeca-3e71-402e-8a80-332f4fb19145">

I can't figure out how to stop it from appearing every time I refresh.

It's still doing it even after the latest update.

**Comment by Weixuanf** [comment]
ohh that's super weird, have you clicked the red button "I have downloaded all my workflows and ready to enable"? If not, can you click that? and refresh again?

**Comment by ManOrMonster** [comment]
Yes, when I click that button, it refreshes the page, then the window appears again.

**Comment by Weixuanf** [comment]
thats weird...are u in cognito mode? but anyways i've pushed a change that will not show this modal anymore if you have enabled twoway sync. you can update to latest version and see if it resolves for you!

> Oh, and I just want to add that this is one of the most important ComfyUI addons by far for me. It's easily as essential as ComfyUI Manager. Thanks for this.

🥹🥹 so glad to hearrr it's useful, hope we can make it better and better! thank you for telling me this!! ❤️

**Comment by ManOrMonster** [comment]
Yes, I was using incognito mode. The update resolved this issue.
