### ISSUE TITLE
choosing folder gives wrong /\

### ISSUE THREAD

**Issue by YacratesWyh** [11cafe/comfyui-workspace-manager#290]
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/8447769/c673d964-00e7-400c-b4e4-74304ad46c80)

![image](https://github.com/11cafe/comfyui-workspace-manager/assets/8447769/e24b1922-11c9-4758-8c4e-22464fa63d91)

it's creating and writing into a wrong folder

**Comment by YacratesWyh** [comment]
Also requires multiple move in ui, now I can only delete or download I guess

**Comment by Weixuanf** [comment]
hi which version are you at? Did you update recently to v2.0? If not can you update to 2.0 first?
________________________________

**Comment by YacratesWyh** [comment]
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/8447769/29a8fa6a-ed2a-4be1-8c3e-d0aa1a75ef53)
checked again, all update.
I guess the reason is the save way is windows, 
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/8447769/1fa49d1a-aea0-4ad7-ad1a-ff9cb4a4be63)

**Comment by Weixuanf** [comment]
what os are you using? windows? macOS?

![Screenshot 2024-03-18 120333](https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/5ac64042-9ef5-48e5-ac77-a6f6f21a8798)
this is in windows, if i click the folder to select path in settings

**Comment by Weixuanf** [comment]
can you click "Reset" button first, then see if it fix it?

**Comment by YacratesWyh** [comment]
I use the web in windows and the server is linux. Reset won't fix this.

**Comment by Weixuanf** [comment]
Hi, should be fixed now, you can pull latest update and see if it works for you :)

sorry I think it's because your server and client are different os and we messed it up
