### ISSUE TITLE
Sort does not affect workflows inside folders any more

### ISSUE THREAD

**Issue by HaydenReeve** [11cafe/comfyui-workspace-manager#292]
I noticed this regression a few days ago, but basically, sort no longer sorts items within a folder for some reason. 

I've fully updated the plugin as well as requirements.txt.

![March-18 (Monday), 22;08;48](https://github.com/11cafe/comfyui-workspace-manager/assets/39004735/c95836b6-eae9-4b3b-ae41-915fe280f60b)

As you can see, the folders are sorted, but not the workflows.

**Comment by Weixuanf** [comment]
thanks for reporting, i think this happens only in subfolder now. will find a fix soon!

**Comment by HaydenReeve** [comment]
Hello! I notice this has now been resolved since the most recent set of updates. I'll close this issue now. Thanks! 👋
