### ISSUE TITLE
[add autosave duration setting, hide files thumbnail settings]Autosave is too aggressive

### ISSUE THREAD

**Issue by Immac** [11cafe/comfyui-workspace-manager#299]
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/3265190/7ea8d779-6c9a-4282-af3f-04900686a08c)
This is me just writing on a textbox, maybe have a cooldown for autosave? Better yet, make the cooldown configurable.

**Comment by Weixuanf** [comment]
we have a 1 second debounce right now, which means that if will batch your changes within a sec. 

But I agree we prob need some better cooldown. But the problem is we have longer cooldown like 30s, you may lose some changes (but I guess in 30s it won't change a lot 🤔) but still, longer cooldown means more risks to lose changes...

or you can disable Auto Save in settings, it can prob improve ui performance since it won't constantly trying to save..

i'm still figuring out what's the best strategy to auto save...welcome any ideas.

**Comment by Immac** [comment]
Well, making the debounce setting configurable would be OK, since I can decide how much I'm willing to risk myself for example.

**Comment by Immac** [comment]
Ideally, having the option to only autosave after a configurable amount of seconds have passed after an important action
, restart the auto save timer each time a new change is made, with the option to force after a configurable amount of time. 
As an example one could configure it to autosave after 20 seconds but force a save if 60 seconds have passed after the first unsaved change, usually autosave is to prevent catastrophic failure from losing most of your work, but autosaving too often leads to performance issues, 30 seconds of unsaved work, or even a minute or two is a palatable tradeoff to having the UI bog down consistently.

**Comment by oliverban** [comment]
+1 for this. Ideally you will let users decide intervals. It makes working really laggy and slow. Also, PLEASE make thumbnails for the workflows an OPTION, I don't want them and they take up too much space.

Also, darkmode <3

**Comment by Weixuanf** [comment]
ok i can add a option in settings:
Auto save duration: Every __ seconds

sorry for late response, really busy and tired these days 🫠 thank you all for the great feedbacks

@oliverban  we already have dark mode support:

<img width="250" alt="Screenshot 2024-03-23 at 1 08 21 AM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/5d71504c-a808-4bd2-83cc-54f9792056c9">

If you still feel UI laggy, please disable auto save in settings!

**Comment by oliverban** [comment]
> ok i can add a option in settings: Auto save duration: Every __ seconds
> 
> sorry for late response, really busy and tired these days 🫠 thank you all for the great feedbacks
> 
> @oliverban we already have dark mode support:
> 
> <img alt="Screenshot 2024-03-23 at 1 08 21 AM" width="250" src="https://private-user-images.githubusercontent.com/18367033/316109921-5d71504c-a808-4bd2-83cc-54f9792056c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNDA3MTYsIm5iZiI6MTcxMTE0MDQxNiwicGF0aCI6Ii8xODM2NzAzMy8zMTYxMDk5MjEtNWQ3MTUwNGMtYTgwOC00YmQyLTgzY2MtNTRmOTc5MjA1NmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDIwNDY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwOTRmYWQwZWRiMDU0N2ZlNmU4OWViZGFhOWE5YzMxNGRlYjQxM2Q1ZjAzOGU0MDJkZTUzNTUxODdjOGRkYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nTXr4MrcpKcqZiM2XVoig1pcfxu5p6b7lTqtrxWCCb8">
> If you still feel UI laggy, please disable auto save in settings!

So awesome, thanks so much! Please feel free to take some days off if need be, we greatly appreciate your efforts - this is one of my fav extensions! <3

**Comment by Immac** [comment]
I think the reason it was trying to save extremely aggressively has to do with Pythongssss autocomplete, might want to check that out.

**Comment by Weixuanf** [comment]
hi i just pushed a change to let you decide the autosave duration, that maybe helpful for the perf issue.

<img width="518" alt="Screenshot 2024-03-27 at 10 42 25 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/ebe386df-6f49-457e-a2ff-dc0ad329e333">

you are welcome to try it out and let me know if it helps with your problem! thank you!

**Comment by Weixuanf** [comment]
> I think the reason it was trying to save extremely aggressively has to do with Pythongssss autocomplete, might want to check that out.

I'm not too sure if it's related 🤔 are you noticing something different when you have autocomplete on/off?

**Comment by Weixuanf** [comment]
> +1 for this. Ideally you will let users decide intervals. It makes working really laggy and slow. Also, PLEASE make thumbnails for the workflows an OPTION, I don't want them and they take up too much space.
> 
> Also, darkmode <3

Thanks very much for your kind words. I'm really glad you are enjoying my work :D I've also added the hide thumbnail option in settings:

<img width="307" alt="Screenshot 2024-03-28 at 12 08 50 AM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/66955a91-60c1-47b0-8142-8e86d09787b2">

I'm feeling a bit better now, finished some long due work. But still hope to take more rest soon...
