### ISSUE TITLE
Slow loading

### ISSUE THREAD

**Issue by Tobe2d** [11cafe/comfyui-workspace-manager#310]
Thank you so much for this amazing addon.

I am facing slowdowns after the last update, and I want to know if there are any limitations to the number of workflows added.

It was very snappy and useful, but now it is slow when searching, loading, etc.

Is there any reason for that?

**Comment by Weixuanf** [comment]
Oh weird… do u happen to know the commit hash or version that you were on before? Or approximately when was your precious “good version” updated at?

Did you change any settings? Like enabled/disabled two way sync, or auto-save, etc.

Were you upgrading from 1.x to 2.0 version? Post v2.0, we are two way sync by default.

Are you using it in local computer or in cloud GPU?

________________________________
From: Tobe2d ***@***.***>
Sent: Tuesday, March 26, 2024 1:32:52 AM
To: 11cafe/comfyui-workspace-manager ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [11cafe/comfyui-workspace-manager] Slow loading (Issue #310)


Thank you so much for this amazing addon.

I am facing slowdowns after the last update, and I want to know if there are any limitations to the number of workflows added.

It was very snappy and useful, but now it is slow when searching, loading, etc.

Is there any reason for that?

**Comment by Weixuanf** [comment]
Hi I just published a change that may improve the performance of loading the side bar workflow list. Please update and see if it works for you! Thank you!

**Comment by Tobe2d** [comment]
Yes it is much better now. thank you!

**Comment by Weixuanf** [comment]
> Yes it is much better now. thank you!

wooo I'm so glad to hear it's working!
