### ISSUE TITLE
Automatic saving and file locking

### ISSUE THREAD

**Issue by liulsg** [11cafe/comfyui-workspace-manager#315]
If I turn on automatic save after locking the file, the file lock will not work. Would it be better to bypass locked files after activating auto save?
File lock is really a very practical feature that can prevent my workflow from being modified during the switching process

**Comment by Weixuanf** [comment]
oops sorry, should be working now, can you update and try it?

**Comment by liulsg** [comment]
Thank you for your hard work, update the latest version can bypass the locked workflow

**Comment by Weixuanf** [comment]
thanks for confirming!
