### ISSUE TITLE
[BUG] This extension changes (breaks) the UI.

### ISSUE THREAD

**Issue by Ratinod** [11cafe/comfyui-workspace-manager#32]
I would like the extension to have no impact on the default UI (indent size, fonts, outlining elements, etc...) at all.

![brokenness](https://github.com/11cafe/comfyui-workspace-manager/assets/12137233/287e6974-daee-44bd-82a2-afe9eb7db3d5)

**Comment by Weixuanf** [comment]
Hi sorry what browser are you using? this is how it looks in Chrome in my machine:
<img width="1220" alt="Screenshot 2023-12-15 at 12 16 50 AM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/380a2098-5aa5-4cfe-b460-5533424cd483">

**Comment by Weixuanf** [comment]
<img width="1081" alt="Screenshot 2023-12-15 at 12 34 37 AM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/662f27d1-df91-48ce-83f7-6efae21a5e4a">

**Comment by Ratinod** [comment]
> what browser are you using

Firefox (If this is still required.)

**Comment by Weixuanf** [comment]
This is helpful, thank you! I have found the root cause, and will have a fix soon. This is caused by the UI framework I’m using, it added some general css styles to give web a more “modern” feel.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Ratinod** [comment]
As I understand it, it is impossible to make sure that the framework you are using does not make changes to the default UI?
Your extension is very useful, I would really like to use it but the broken original UI is stopping me.
<sub><sub>I just don't want completely unnecessary "modern" changes to the UI. Something like this should come as a separate extension.</sub></sub>

**Comment by Weixuanf** [comment]
Hi it is possible to fix. I already have a draft just need more polishing! Sorry for the delay, I got caught up on some other work 😢 will do this asap!

**Comment by Ratinod** [comment]
There is no need to rush, everyone has their own things to do, which of course are more important. I'm glad to hear that this can be fixed. I'll just wait.

**Comment by Weixuanf** [comment]
i just published the new version: https://github.com/11cafe/comfyui-workspace-manager/pull/85

install the latest extension and this problem should be fixed.

**Comment by Ratinod** [comment]
Unfortunately, almost everything remained unchanged (as in the first picture I posted).
The only place where there are changes is "settings".
Now the drop-down lists have become white and their contents are almost impossible to see. (However, the disconnected checkboxes are now not replaced in black, now they are white as they should be on default.)

**Comment by Weixuanf** [comment]
<img width="1682" alt="Screenshot 2024-01-09 at 10 34 45 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/c69227ec-e06c-40ef-8c48-2ca7fff4bbf8">
<img width="1425" alt="Screenshot 2024-01-09 at 10 35 15 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/cc097db7-98e5-4863-b15b-7c26556f8406">

**Comment by Weixuanf** [comment]
settings page on firefox
<img width="1010" alt="Screenshot 2024-01-09 at 10 39 17 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/75e9e6e2-bb98-466c-ab02-94528d0355b7">

**Comment by Ratinod** [comment]
> can you try deleting the extension and reinstall again

I confirm. Completely deleting the extension folder and reinstalling it fixes everything.
Thank you very much for this fix.

**Comment by Weixuanf** [comment]
Yayyy
