### ISSUE TITLE
ComfyUI freezes with save_db Request Entity Too Large error

### ISSUE THREAD

**Issue by pto2k** [11cafe/comfyui-workspace-manager#325]
Hi,
Around yesterday, after updating everything, ComfyUI interface completely freezes every few seconds with the error:
POST http://127.0.0.1:8188/workspace/save_db 413 (Request Entity Too Large)

I set auto-save of workspace manager to off, but it does not help right away. I rebooted comfy and now the error and freeze have stopped. 

![Snipaste_2024-03-28_22-53-13](https://github.com/11cafe/comfyui-workspace-manager/assets/4364117/2c39e3f1-c1be-4369-8866-1e92a189d0a1)

**Comment by Weixuanf** [comment]
<img width="712" alt="Screenshot 2024-03-28 at 11 41 06 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/b7639dc2-6f57-4440-ba2c-a977d8dc4599">

hi can you help check network tab and screenshot the network payload for me? thank you!

**Comment by Weixuanf** [comment]
<img width="816" alt="Screenshot 2024-03-28 at 11 42 38 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/a42ab426-fcf3-47ba-a20d-895340629b82">

make sure you screenshot the payload size too

**Comment by Weixuanf** [comment]
<img width="501" alt="Screenshot 2024-03-28 at 11 48 36 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/018c8a92-f4fa-46e6-a6d9-e1c27cc81dcf">

in your settings, can you change this settings to a lower number like 10 or 20, to see if it helps with the issue?

**Comment by pto2k** [comment]
Got screenshot of the payload, it is 10MB
![Snipaste_2024-03-28_23-50-20](https://github.com/11cafe/comfyui-workspace-manager/assets/4364117/cb0c9c5c-31df-4640-8452-152baa44ab55)

I'll try changing the setting.

My folder of workflows has 96 json files with a total size of 3.3MB

**Comment by Weixuanf** [comment]
> I'll try changing the setting.
> 
> My folder of workflows has 96 json files with a total size of 3.3MB

thanks for digging in. I just published a change that may help with this. We are planning to migrate our backend db to sqlite to properly mitigate this issue too in long term.

**Comment by pto2k** [comment]
Thanks! I'll try to update.
I've just lowered the version history number, and also cleared all files in my workflow folder. but seems the payload is till 10.3MB.
I checked the db folder and saw that the changelogs file is very big.
![Snipaste_2024-03-29_00-11-50](https://github.com/11cafe/comfyui-workspace-manager/assets/4364117/f2a4db50-cea0-4901-b28f-b9dd4296d9c9)

**Comment by Weixuanf** [comment]
Right the main problem is the changelogs table. I’ve changed the code to not store it to disk anymore. They will now only be stored in browser db (they are not that important so not worth it to backup into disk i think, especially when they can become very big..)
________________________________

**Comment by Weixuanf** [comment]
The workflows payload you're seeing (10.3MB) cannot be reduced now cuz we still need to backup them into disk. But in future we plan to migrate server db to reduce payload size fundamentally.
________________________________

**Comment by pto2k** [comment]
Thanks for the explanation.  And the fix seems to be working =) no more errors

Another question, for the auto-save, does it save on every change in the graph? 
If so, I wonder if you can add an option to exclude changes that do not affect the outcome of the graph, for example, node positions, color, etc.. and so they do not save into versions.

**Comment by pto2k** [comment]
Thank you very much for the quick fix!
