### ISSUE TITLE
Install Models broken: models_v5 no longer works as search index

### ISSUE THREAD

**Issue by rconstantine** [11cafe/comfyui-workspace-manager#329]
From a user perspective, the spinner just spins when you open Install Models. Looking at the browser console and also Network->Response, it appears the index "models_v5" is no longer valid. This is the error in Network->Response in Dev Tools:

{
    "message": "Inside `.queries[0]`: Index `models_v5` not found.",
    "code": "index_not_found",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#index_not_found"
}

**Comment by Weixuanf** [comment]
Hi please upgrade to latest version and it will be fixed
________________________________
From: rconstantine ***@***.***>
Sent: Sunday, March 31, 2024 5:25:35 AM
To: 11cafe/comfyui-workspace-manager ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [11cafe/comfyui-workspace-manager] Install Models broken: models_v5 no longer works as search index (Issue #329)


From a user perspective, the spinner just spins when you open Install Models. Looking at the browser console and also Network->Response, it appears the index "models_v5" is no longer valid. This is the error in Network->Response in Dev Tools:

{
"message": "Inside .queries[0]: Index models_v5 not found.",
"code": "index_not_found",
"type": "invalid_request",
"link": "https://docs.meilisearch.com/errors#index_not_found"
}

**Comment by rconstantine** [comment]
Sweet. That did the trick. I have just a few models that aren't available on Civitai. Any chance we could have an option to point those particular ones to a URL that we enter? If you think that is possible, I can open a feature request. If not, that's OK. Great job on this module. Many thanks.

**Comment by Weixuanf** [comment]
> Sweet. That did the trick. I have just a few models that aren't available on Civitai. Any chance we could have an option to point those particular ones to a URL that we enter? If you think that is possible, I can open a feature request. If not, that's OK. Great job on this module. Many thanks.

It's possible but which website would that be from? I'm not sure if I can get thumbnail image from any website you enter. If we can't get the thumbnail image from the url, then do you see it's useful to set the customize url?

**Comment by rconstantine** [comment]
The site is Tensor.art. If you go to the models section, you can see that some are marked “exclusive”.  They do have thumbnails, but whether there is an api for grabbing them or you’d have to scrape them, I don’t know. I also don’t know what they use for unique identification of each model.
It’s not a big deal, really. I was just curious since the browser console had so many errors attempting to retrieve them. As a developer myself, I just prefer to have no errors. If the civitai API has a way to ask about the existence of a model before attempting to download data about it, then that would work too.


Ryan Constantine

On Sunday, March 31, 2024, 8:42 AM, Weixuan Fu ***@***.***> wrote:





Sweet. That did the trick. I have just a few models that aren't available on Civitai. Any chance we could have an option to point those particular ones to a URL that we enter? If you think that is possible, I can open a feature request. If not, that's OK. Great job on this module. Many thanks.


It's possible but which website would that be from? I'm not sure if I can get thumbnail image from any website you enter. If we can't get the thumbnail image from the url, then do you see it's useful to set the customize url?

**Comment by Weixuanf** [comment]
> . I was just curious since the browser console had so many errors attempting to retrieve them. As a developer myself, I just prefer to have no errors. 
I also found that annoying :( I prob need to cache the response result and don't request again for the ones that non existing in civitai...
