### ISSUE TITLE
thumbnail changes when  workflow excuted

### ISSUE THREAD

**Issue by heckles** [11cafe/comfyui-workspace-manager#330]
Appriciation for your excellent extension!
but i got a problom:
 i chose and uploaded thumbnails for each of my workflow, since i updated to the version 61a899a, once my workflow been excuted, the thumbnail changed

**Comment by heckles** [comment]
in previous version, there was an option "set as cover", that would work for me

**Comment by Weixuanf** [comment]
<img width="485" alt="Screenshot 2024-03-31 at 11 25 36 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/bcbf3943-d8da-4ee8-b312-a8a95df65f42">

Hi fixed now, you can set as cover as before. and uploaded thumbnail shouldn't be overrided with new generations anymore

**Comment by heckles** [comment]
thanks a lot!
