### ISSUE TITLE
Save keybinding (SHIFT+S) blocks entering text

### ISSUE THREAD

**Issue by darkpixel** [11cafe/comfyui-workspace-manager#332]
I was trying to enter the text ```SEED: ``` into a debug box and couldn't get it to create an 'S'.
It totally works with lowercase 's'.
Looks like the save keybinding is preventing entering capital 'S' characters in text boxes.

Workaround: Type ```SEED: ``` into your favorite text editor, copy, paste.

**Comment by Weixuanf** [comment]
Hi, I'll publish a fix for this soon, before that, can you please change the shortcut from shift+S to something else for save workflow in settings?

**Comment by darkpixel** [comment]
Nice--I didn't even think of capslock and then tapping 's'. :)

It's no worries--I'm able to work around the issue until a fix is published.

**Comment by Weixuanf** [comment]
Hi main branch should be fixed now!

> Nice--I didn't even think of capslock and then tapping 's'. :)

haha I never thought of shift+anything for caps, so used to caps lock
