### ISSUE TITLE
Linux Debain 上 从URL下载模型文件名后携带`";`特殊符号

### ISSUE THREAD

**Issue by Llugaes** [11cafe/comfyui-workspace-manager#339]
环境：Debian GNU/Linux 11

模型链接：https://huggingface.co/comfyanonymous/ControlNet-v1-1_fp16_safetensors/resolve/main/control_lora_rank128_v11f1e_sd15_tile_fp16.safetensors

错误示例：
<img width="736" alt="filename_error" src="https://github.com/11cafe/comfyui-workspace-manager/assets/43494187/92cdd2b6-486f-4910-9a3e-c4d38d220cf3">

解决方法：
<img width="761" alt="force_filename" src="https://github.com/11cafe/comfyui-workspace-manager/assets/43494187/8e9e8ac5-5828-4351-86bc-99b38053a18d">

成功示例：
<img width="655" alt="filename_correct" src="https://github.com/11cafe/comfyui-workspace-manager/assets/43494187/4dafff8e-3b90-422f-824d-e25bc617b682">

大佬能看一下具体是什么问题吗？或者加个开关可以让我toggle这个force_filename？
像这种问题很多通过链接下载的模型都有，而且只有Linux上出现了，Windows上没有这个问题，目前我暂时写死为True就能解决这个问题，但是很明显是不可持续的，我没有太多时间阅览源码，所以不好贸然提pr，还请大佬定位一下是什么问题，并提供一个官方的解决方案😿plz

**Comment by Weixuanf** [comment]
hi thanks for reporting, 刚改了一下 应该修好了 你试试吧～感谢提供了code pointer，加快了我debug哈哈

**Comment by Llugaes** [comment]
赞👍 测试了一下没问题了， 感谢！
