### ISSUE TITLE
感觉 UI 交互有点问题，一直在抖动的感觉

### ISSUE THREAD

**Issue by U-DI-Page** [11cafe/comfyui-workspace-manager#343]
https://github.com/11cafe/comfyui-workspace-manager/assets/14305674/fc7f737e-dc6f-41e5-8ca7-c7d1c7fc96bf

**Comment by Weixuanf** [comment]
windows？edge浏览器吗？

**Comment by U-DI-Page** [comment]
> windows？edge浏览器吗？

windows chrome 浏览器

**Comment by Weixuanf** [comment]
我试了下windows chrome和edge上没法repro出这个问题 你要不更新下插件试试？

**Comment by U-DI-Page** [comment]
> 我试了下windows chrome和edge上没法repro出这个问题 你要不更新下插件试试？

是没有固定高度的问题，因为后面的日期占了两行，你鼠标悬停上去变成了一行按钮，所以视觉上看就有点抖动的感觉，设为固定高度应该就可以解决了

**Comment by Weixuanf** [comment]
ok好的！我回头改一下 谢谢你！
________________________________

**Comment by Weixuanf** [comment]
更新了一下， 你看看现在还有这个问题吗 最新版

**Comment by U-DI-Page** [comment]
> 更新了一下， 你看看现在还有这个问题吗 最新版

正常了！👍
