### ISSUE TITLE
UI严重bug，不带缩略图的workflow目前无法删除，鼠标悬停后自动消失

### ISSUE THREAD

**Issue by LiJT** [11cafe/comfyui-workspace-manager#351]
![PixPin_2024-04-18_17-46-11](https://github.com/11cafe/comfyui-workspace-manager/assets/11270197/77130ae2-885a-47b9-9055-8bcfbf119f38)

请看，鼠标悬停到删除按键附近，因为这个时候已经到了下方工作流的上方，这个删除框就消失了，无法按下去，目前只能手动去custom workflow里自己去删除，非常麻烦

**Comment by Weixuanf** [comment]
hi 更新一下版本哦 最新版应该没有这个问题了呢
