### ISSUE TITLE
Workflow List Blank after last update

### ISSUE THREAD

**Issue by formulake** [11cafe/comfyui-workspace-manager#368]
I don't think the title needs much explaining. I had a large number of workflows meticulously arranged by folder. Then along comes the update and wipes them all out.

**Comment by Weixuanf** [comment]
😱😱the workflows in your disk /my_workflows folder are all deleted??
Any errors in python console?
________________________________
From: formulake ***@***.***>
Sent: Saturday, May 11, 2024 12:15:21 PM
To: 11cafe/comfyui-workspace-manager ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [11cafe/comfyui-workspace-manager] Workflow List Blank after last update (Issue #368)


I don't think the title needs much explaining. I had a large number of workflows meticulously arranged by folder. Then along comes the update and wipes them all out.

**Comment by Weixuanf** [comment]
The json files are all deleted?
________________________________

**Comment by formulake** [comment]
I can't locate the JSON files anywhere. I ran a full system search as well. It's all just gone. I really liked this QoL node but I just can't afford to have this happen again so unfortunately I don't think I'll be able to go back to it again.

**Comment by Weixuanf** [comment]
![IMG_6635](https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/339703b1-12ab-4a85-b305-22ba1b60ce95)

Have you ever seen this dialogue when you upgrade plugin?

can you also F12 -> Application IndexedDB -> workflows table and see if you still have data there?

can can you also go to comfyui-workspace-manager/db/workflows.json and see if it has any data? If yes can u paste it and I’ll see if I can recover if for you

**Comment by Weixuanf** [comment]
<img width="607" alt="IMG_6636" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/0d60f048-a041-4bce-a13b-69b8fa9be3be">

indexdb data should look like this, if this is not empty, it can still be recovered

**Comment by formulake** [comment]
I tried something else. First I moved the comfyui-workspace-manager folder out of the custom_nodes folder and started up comfyUI. I then copied it back in and restarted and this seems to have done the trick and I have my workflows back. It's a really great QoL node that I use almost exclusively for my workspace management, but it did give me quite the fright :) I'm glad it's back to normal though and I don't have to stop using it.
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/7622615/7228feda-e567-4978-a210-f664749e15d4)

**Comment by Weixuanf** [comment]
umm this sounds really weird..i'm still trying to understand what's happening.

1. workspace manager just displays the .json files in the folder directory in your disk that you choose for your /my_workflows folder. If the folder is empty then your list is empty; if the folder has any .json files then it will display exactly the .json files. 
So make sure that you have chosen a valid folder directory in settings here to store your workflows:

<img width="381" alt="Screenshot 2024-05-11 at 11 12 14 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/d2923c5b-a020-4778-8ca8-6c8c70174aa9">

3. **please BACKUP this /my_workflows/ folder occasionally.** This folder contains all your workflows .json, it is very important. Some of our users use git to backup this folder (https://product.hubspot.com/blog/git-and-github-tutorial-for-beginners)  Or you can use dropbox or google drive to backup it to cloud. Or you can just manually copy this folder for backup occasionally. **Or you can just select all and "download zip" occasionally to backup all your workflows**

<img width="259" alt="Screenshot 2024-05-11 at 11 23 42 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/bf00d251-c0d3-44ed-b5f7-2841436ebf70">


Maybe we should do some backup automatically for you in future. But right now, please backup everything yourself occasionally so you don't experience any disaster

**Comment by Weixuanf** [comment]
so right now, can you exam what's your "Workspace Save Directory" in settings, and can you please backup everything in that folder? backup to another folder location, to cloud drive, to git, etc.

**Comment by Weixuanf** [comment]
sorry for the inconvenience, i should add some better backup functionality, cloud backup, git backup, etc.

**Comment by formulake** [comment]
ComfyUI/my_workflows has json files but they aren't all the workflows that show up in the menu. That's really weird. I really can't seem to locate where it's saving them. This is the sum total of workflows in there and, as you can see, none of the jsons from my previous screenshot are in here, nor is any of the folder structure.
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/7622615/af329db8-d24c-4b3b-8217-1b460fb0b71a)
I haven't used a custom full path either
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/7622615/661cca7c-eb2d-49db-9035-89806b7675c0)
When I click on the "Open Workspace Save Directory" icon it strangely leads to my user/documents folder where there is no folder containing the files.
I think the best way for me to stay safe for now is to download the zip, as you've suggested, and keep a cloud backup of it.

I appreciate you engaging on this subject and greatly appreciate the functionality your node brings to ComfyUI.

**Comment by Weixuanf** [comment]
ok I see what's going on.

1. make sure you enabled two way sync in settings

<img width="495" alt="Screenshot 2024-05-12 at 10 31 52 AM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/d4e234ca-eb1a-44e6-86c8-a118d433264c">

2. please re-select your My Workflows Save Directory. Your current selected path is invalid, as it is showing "undefined"
Click the folder icon and reset the directory:

<img width="514" alt="Screenshot 2024-05-12 at 10 33 17 AM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/0785a55e-a24c-4704-a9ee-8391ad8c7e85">

**Comment by Weixuanf** [comment]
I really appreciate your sponsor. Thanks a lot. Workspace manager is not yet perfect, so I'm eager to learn what issues you are experiencing and I hope to make it less errors and issues. Thanks for reporting this issue. 

I think I should enforce some validation checks against your selected "Workflows Save Directory" path.

**Comment by formulake** [comment]
Sorry about the late reply. I'm travelling all of this week but I'll be sure to run the steps you've suggested once I'm back. Thanks for all your effort. It makes a big difference!

**Comment by formulake** [comment]
Just thought I'd provide a quick update on this. I got back and ran your steps, reset the folder path and this time I gave it an absolute path. Life is back to normal again :) Thanks again for your help.
