### ISSUE TITLE
> > @Weixuanf 同样阿里云dsw 转发出现问题，端口转发错误启动不了

### ISSUE THREAD

**Issue by TonyDua** [11cafe/comfyui-workspace-manager#375]
> > @Weixuanf 同样阿里云dsw 转发出现问题，端口转发错误启动不了
> 
> 嗯 我过两天修一下

搞了个域名挂载替代127.0.0.1:8188地址就可以了，也是无语阿里云瞎搞多了一层workspace_web的层级搞得一大堆插件都挂了
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/16109867/9dd4f0fe-9a17-49ce-b7f7-34859eaaeed2)
不过还是有个反推插件挂了：/extensions/pysssss/WD14Tagger/wd14tagger.js TypeError: Failed to fetch dynamically imported module:

_Originally posted by @TheBloodthirster in https://github.com/11cafe/comfyui-workspace-manager/issues/218#issuecomment-2077659646_
            请问大佬如何挂载的域名？

**Comment by Weixuanf** [comment]
可以再试一下 我修了一下在最新的版本，看看有没有修好
