### ISSUE TITLE
Very disappointed. My ComfyUI is destroyed after installing this on Mac.

### ISSUE THREAD

**Issue by tsevis** [11cafe/comfyui-workspace-manager#379]
Yesterday I installed this custom node. Unfortunately after that I am only producing black images.
I have uninstalled it, fresh installed ComfyUI but still having the same issue.
Any help?
Thanks in advance!

C.

**Comment by Weixuanf** [comment]
> I have uninstalled it, fresh installed ComfyUI but still having the same issue

I don’t think it’s related to workspace manager then if you already deleted the plugin from custom nodes folder…this plugin only take effect when you have it installed. It doesn’t change other files in your comfyui or computer.

As for producing black images, maybe try asking in some comfyui community? I’m not too sure about it. Do you have the right models downloaded?
