### ISSUE TITLE
自动保存的逻辑真的狗屎

### ISSUE THREAD

**Issue by acolasialiuliu** [11cafe/comfyui-workspace-manager#380]
三秒存一次，默认文件名和工程文件名总是混乱，怎么切换都是同一个，如果赶上这个bug依然在，你切换到别的文件，那么好了，三秒后你这个名字的文件就被替换了，你tm，，，，，，，，，，浪费我一天的成果不说两句不行

**Comment by Weixuanf** [comment]
实在抱歉。您是在最新版本吗？如果您关闭自动保存，用手动保存还有遇到问题吗😥

也许后续会考虑彻底取消自动保存了吧 如果自动保存错误太多的话

**Comment by acolasialiuliu** [comment]
唉，手动没问题，但是自动保存就失去意义了。建议自动保存加备份，备份单独设置一个文件夹。还有那个双向同步没看懂谁跟谁双向同步。我们也可以在指定一个文件夹作为同步备份文件夹。现在的自动保存只会覆盖，连副本都不留。太可怕了。

**Comment by Weixuanf** [comment]
> 建议自动保存加备份，备份单独设置一个文件夹。

**Comment by Weixuanf** [comment]
> 建议自动保存加备份，备份单独设置一个文件夹。

这个实现起来估计难度比较大，可能之后考虑取消自动保存功能吧，确实有点容易出错。

确实自动备份的功能我有在考虑加，可能就每隔一天去备份一遍你全部的json workflow吧 单独存放在一个comfyui/workflow——backups 之类的文件夹里 🤔

> 还有那个双向同步没看懂谁跟谁双向同步。

这个意思是和你选择的本地文件夹进行双向同步，`ComfyUI/my_workflows` 默认是这个文件夹，所有的工作流都是直接从你选定的本地文件夹中读写json。这个一定要保持在打开状态哦，未来会强制打开two way sync。（因为之前工作流是存储在浏览器数据库里的，所以称为单项同步）

**Comment by acolasialiuliu** [comment]
现在这俩功能就糟糕了，保存出问题的情况下，同步过来的也是错的。工具是好工具，确实缺少这么个东西，感谢回复。

**Comment by Weixuanf** [comment]
<img width="313" alt="Screenshot 2024-05-20 at 5 15 08 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/dbd5b0ff-72a8-4129-80d2-8371359de81c">


<img width="409" alt="Screenshot 2024-05-20 at 5 15 04 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/818d5f09-175f-4414-91c7-7b8bf361fbd0">


其实每次自动保存是有version history（更改记录的） 你去下来菜单的version history里能找到

**Comment by acolasialiuliu** [comment]
是的我看到了，但是不知道为什么，记录只有昨天下午六点的，而我最后的工程在昨晚一点左右。中间都没有进行自动保存，可能是由于期间我的工作流导致显存炸了然后保存出了问题

**Comment by acolasialiuliu** [comment]
然而今天我启动cfui，默认会打开我之前的工作流，是没问题的，这会儿也就是今天下午，我看了第一次自动保存的记录，依然不是刚启动那会儿的进度，还是昨天下午六点的。

**Comment by Weixuanf** [comment]
umm可能自动保存确实有些许问题 我回头得在测试测试。。。不行的话就把自动保存功能删了吧。功能/模式太多的话容易测试不过各种情况从而产生bug，我打算精简一下功能，保证核心功能正确。

**Comment by Weixuanf** [comment]
另外这个自动保存的历史记录是存在浏览器数据库的，所以你中途换了浏览器的话会出问题。

**Comment by acolasialiuliu** [comment]
没换浏览器，我现在嘎嘎手动保存

**Comment by Weixuanf** [comment]
> 没换浏览器，我现在嘎嘎手动保存

hh 好吧～我回头再测试debug一下自动保存吧 感谢你的report，之后如果手动保存再遇到什么问题也欢迎report。希望我们能越来越完善问题越来越少吧！

谢谢～
