### ISSUE TITLE
Problem with Models feature

### ISSUE THREAD

**Issue by ManOrMonster** [11cafe/comfyui-workspace-manager#381]
The Models button has never worked for me. I have 500 GB of LORAs, and whenever I click that button, it rebuilds from scratch, takes forever, and slows down my generations. When I accidentally click that button, things grind to a halt and I have to restart ComfyUI.

Can we get an option to hide that button? If it worked well with thousands of files, it would be great, but it just doesn't from my experience.

**Comment by Weixuanf** [comment]
ohhh i see...I'll see if I can add a option to hide the button!

**Comment by Ainaemaet** [comment]
> The Models button has never worked for me. I have 500 GB of LORAs, and whenever I click that button, it rebuilds from scratch, takes forever, and slows down my generations. When I accidentally click that button, things grind to a halt and I have to restart ComfyUI.
> 
> Can we get an option to hide that button? If it worked well with thousands of files, it would be great, but it just doesn't from my experience.

500GB of LORA's is _insane_., as they are typically rarely much over 1gb. Not to try to tell a guy what to do, but why not offload some of them to a storage disk, and keep the ones you are currently working with on your work disk?

**Comment by ManOrMonster** [comment]
This is not a problem in StableSwarmUI or WebUI.

> 500GB of LORA's is _insane_., as they are typically rarely much over 1gb. Not to try to tell a guy what to do, but why not offload some of them to a storage disk, and keep the ones you are currently working with on your work disk?
