### ISSUE TITLE
点击某个工作流右边的三个点，没有重命名选项。。

### ISSUE THREAD

**Issue by AlexanderDash** [11cafe/comfyui-workspace-manager#389]
加一个重命名json文件的选项。。

**Comment by Weixuanf** [comment]
<img width="394" alt="Screenshot 2024-05-27 at 6 58 13 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/42f17843-644e-4a33-8c30-010ca3ea30bd">
<img width="460" alt="Screenshot 2024-05-27 at 6 58 16 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/36f77605-01ae-4ee4-a055-b3046f93ce14">
