### ISSUE TITLE
Unable to find workflow in example.png

### ISSUE THREAD

**Issue by Zanedname** [11cafe/comfyui-workspace-manager#392]
![20240528132800](https://github.com/11cafe/comfyui-workspace-manager/assets/155146890/78bf2e86-4775-44dc-9fbf-c2cf6ca471ba)
Hello, I'm curious if the feature of reading workflows from images is related to the workspace itself. I've encountered an issue where, every time I try to drag PNG/JPG files that contain workflows into ComfyUI—including examples from new plugins and unfamiliar PNGs that I've never brought into ComfyUI before—I receive a notification stating that the workflow cannot be read. Strikingly, PNG files that I had imported into ComfyUI previously can still have their workflows recognized without any problems!

Despite trying multiple different ComfyUI package integrations, the issue remains unresolved. Could you shed some light on why this might be occurring or recommend steps for addressing it?

**Comment by Weixuanf** [comment]
hi i don't think this is related to comfyui workspace manager. its probably the problem with comfyui itself.

**Comment by Zanedname** [comment]
OK, although I answered very late, thank you very much. I have solved it myself and there is no problem

**Comment by mxteaw** [comment]
I had the same problem, how did you solve it?

**Comment by mxteaw** [comment]
> OK, although I answered very late, thank you very much. I have solved it myself and there is no problem

I had the same problem, how did you solve it?

> OK, although I answered very late, thank you very much. I have solved it myself and there is no problem



> OK, although I answered very late, thank you very much. I have solved it myself and there is no problem

I had the same problem, how did you solve it?

**Comment by mxteaw** [comment]
> OK, although I answered very late, thank you very much. I have solved it myself and there is no problem

I had the same problem, how did you solve it?
