### ISSUE TITLE
[small bug] Locked workflow asks me to save

### ISSUE THREAD

**Issue by LukeG89** [11cafe/comfyui-workspace-manager#393]
Hi, I would like to report a small bug that I've been experiencing for the past two weeks or so.

Even though I locked a workflow months ago, everytime I startup ComfyUI it shows me the "*" like it's unsaved.

![locked_flow](https://github.com/11cafe/comfyui-workspace-manager/assets/161304036/2ccaa3c5-9d8f-4a78-86b1-bb6233479930)

When I switch to another workflow, it asks me to save or discard.

![save_discard](https://github.com/11cafe/comfyui-workspace-manager/assets/161304036/22c3c93e-dff2-4add-a096-26d35c0957f1)

If I click save it tells me that it can't be saved because it's locked.

**Comment by Weixuanf** [comment]
hi should be fixed in the new version, let me know if you are still experiencing the issue.
