### ISSUE TITLE
模型模块打开无内容

### ISSUE THREAD

**Issue by hotren1977** [11cafe/comfyui-workspace-manager#404]
升级到[74c2efa]后，不管是本机模型或者安装模型都无法显示内容，回滚到上一版本就可以正常显示，都是已开代理的状态

**Comment by Weixuanf** [comment]
thanks for reporting, will be fixed once https://github.com/11cafe/comfyui-workspace-manager/pull/405 is merged. I plan to merge to tomorrow

**Comment by Weixuanf** [comment]
新版本发了，更新一下应该就好了
