### ISSUE TITLE
Failed to load resource: the server responded with a status of 400 (Bad Request)

### ISSUE THREAD

**Issue by VipCrazyMaster** [11cafe/comfyui-workspace-manager#41]
Plug-ins can be used, but running a debug window on the web will prompt for an error
<img width="1667" alt="1702735576423" src="https://github.com/11cafe/comfyui-workspace-manager/assets/137988107/a3463172-54ef-4d09-84c7-e341f06b451c">

Failed to load resource: the server responded with a status of 400 (Bad Request)
:8188/workspace/get_db?table=tags:1 
        
        
       Failed to load resource: the server responded with a status of 400 (Bad Request)
:8188/workspace/get_db?table=userSettings:1 
        
        
       Failed to load resource: the server responded with a status of 400 (Bad Request)

--------------------------------------------------------------------------------------------------------
System environment
Macbook M1 pro  Chrome 120.0.6099.109（正式版本） (arm64)
ComfyUI: 1832[e45d92](2023-12-16)
Manager: V1.14

**Comment by Weixuanf** [comment]
hi thanks for reporting, no need to worry to much about this error, it's because you haven't added some settings and tags and that's why it couldn't find these table. I should bypass these errors in future versions. as long as they are not breaking experiences, it should be fine

**Comment by VipCrazyMaster** [comment]
I see, thank you very much for the creation of this plug-in, very easy to use!

**Comment by Weixuanf** [comment]
aww, thank you very very much for you support! ❤️ please feel free to suggest any feedbacks or improvements ☺️ we are constantly updating new feature. the new drag and drop insert workflow feature just came out! :)

> I see, thank you very much for the creation of this plug-in, very easy to use!
