### ISSUE TITLE
刚更新了最新版本,左上角不显示了工作流管理

### ISSUE THREAD

**Issue by zhangjinyan888** [11cafe/comfyui-workspace-manager#419]
刚更新了最新版本,左上角不显示了工作流管理

**Comment by Weixuanf** [comment]
奇怪，python控制台或者网页f12控制台有什么报错吗

**Comment by Weixuanf** [comment]
你是不是更新了comfyui 我刚发现我更新了最新comfyui也出现这个问题了，我现在修一下

**Comment by ArtliveBear** [comment]
我的不显示工作流管理和模型的按钮了，卸载重装了几遍都无效，请问是插件bug还是我设置问题，要怎么调出来那些菜单栏呢？

**Comment by ArtliveBear** [comment]
我刚刚从这里直接下载了压缩包，现在可以显示了，看更新时间貌似是刚刚更新的，谢谢！

**Comment by Weixuanf** [comment]
嗯 刚刚修好了

**Comment by Weixuanf** [comment]
不过最好还是从comfyui manager里面更新安装哦 因为有pip package需要安装 自己下的压缩包是没有需要的pip package的！

**Comment by ArtliveBear** [comment]
好的，谢谢，那我再重新安装一次

**Comment by ArtliveBear** [comment]
很遗憾的是从comfyui manager里面安装还是不显示，可能后台还没有更新还是怎么回事，我只能从comfyui manager安装后再用从这里下载的压缩包内的文件替换掉从comfyui manager下载的安装文件。目前解决

**Comment by Weixuanf** [comment]
也有可能是浏览器缓存一些静态文件的问题，有时候需要关掉浏览器重开

**Comment by zhangjinyan888** [comment]
已经更新解决

**Comment by shmilyfuu** [comment]
> 不过最好还是从comfyui manager里面更新安装哦 因为有pip package需要安装 自己下的压缩包是没有需要的pip package的！

@Weixuanf 您好，请问一下pip package是更新安装包里面的requirements.txt吗，我手动更新的时候pip install ..\comfyui-workspace-manager会报错，查看是pyproject.toml 文件中的配置错误导致的

**Comment by Alvinperson** [comment]
> 你是不是更新了comfyui 我刚发现我更新了最新comfyui也出现这个问题了，我现在修一下

你是咋修的？
