### ISSUE TITLE
旧版保存在comfyui-workspace-manager\db\workflows.json的工作流该如何导入到新版的插件中

### ISSUE THREAD

**Issue by spocel** [11cafe/comfyui-workspace-manager#437]
因为想更新所有插件，而comfy ui使用的是2024.1月的版本，自动更新不生效，我将插件文件备份后删除并重新下载了新的插件，发现工作流被保存在了ComfyUI\my_workflows中，两种json文件格式不同导致无法正确导入，请问我该如何导入？原插件的所有文件都已备份，原插件版本为1.1.0

**Comment by Weixuanf** [comment]
两种json文件格式不同是为什么？你就直接拖拽json到comfyui画布上是可以打开的吧？

你在新版本的settings里面 reset一下my workflows的文件夹地址 指向你workflows json文件的存储地址就行了
________________________________
From: spocel ***@***.***>
Sent: Sunday, July 14, 2024 2:32:47 PM
To: 11cafe/comfyui-workspace-manager ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [11cafe/comfyui-workspace-manager] 旧版保存在comfyui-workspace-manager\db\workflows.json的工作流该如何导入到新版的插件中 (Issue #437)


因为想更新所有插件，而comfy ui使用的是2024.1月的版本，自动更新不生效，我将插件文件备份后删除并重新下载了新的插件，发现工作流被保存在了ComfyUI\my_workflows中，两种json文件格式不同导致无法正确导入，请问我该如何导入？原插件的所有文件都已备份，原插件版本为1.1.0

―

**Comment by spocel** [comment]
我这个workflows.json文件保存了从我下载comfyui以来所有的工作流....他的大小有10.430MB，他和正常的工作流不一样，无论是拖拽或者是导入都没办法正常导入...

**Comment by spocel** [comment]
我仔细查找了一下，这个db内的workflows指向了一个文件夹，这个文件夹保存了我所有的工作流，现在找到了，没事了，但还是谢谢回复

**Comment by Weixuanf** [comment]
好的好的 你解决了就行！有问题再随时问我
________________________________
