### ISSUE TITLE
[Easy Feature Request] Add a save button

### ISSUE THREAD

**Issue by AlexanderDash** [11cafe/comfyui-workspace-manager#48]
Click on the official Save button and a text box will pop up with the default input of "workflow. json". I have to change the name every time, which is too troublesome. If I use your comfyui workspace manager, I think I can click on a new save button and download it directly based on the current workflow name

**Comment by Weixuanf** [comment]
hi the version i just published added "Download" button that should do what you described:
<img width="409" alt="Screenshot 2023-12-27 at 11 16 21 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/24f45403-cb2e-47ee-8119-8a2799a98560">
it will be downloaded directly as the name of your workflow
