### ISSUE TITLE
【bug】workflow manager layer display error

### ISSUE THREAD

**Issue by allen-studio** [11cafe/comfyui-workspace-manager#49]
### layer error
Layer display error when workflow panel is on input node
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/26627761/2554f897-3e79-4867-8196-1b7af4234dd4)

**Comment by Weixuanf** [comment]
what node is this? CLIP text or some other node?

**Comment by allen-studio** [comment]
yes it's clip text encoder node，but i just tried it，I couldn‘t reproduce this problem .

**Comment by Weixuanf** [comment]
oh ok, so is this problem gone now? I've tried the text encode node too, and can't repro.

**Comment by allen-studio** [comment]
it's ok now,thx.I will close this comment.
