### ISSUE TITLE
Auto save needs to go away.

### ISSUE THREAD

**Issue by dchatel** [11cafe/comfyui-workspace-manager#52]
I really want to like and use this custom node, because managing workflows with json files is quite painful, but the auto save feature needs to go away and be replaced by a simple "new/load/save" system.

Right now, if I have a workflow loaded, and make a small change to it, but I don't want to persist that change, I can't, because the change will persist.
Even worse : if I have a workflow loaded (and named), and drag drop a json file on comfyui, the workflow in the json will overwrite the previously loaded named workflow, whereas it's quite obvious that the intended behavior would have been to create a new workflow unnamed workflow and load the json here, without erasing the old workflow.

Or maybe I'm doing it all wrong, I'm not sure.

**Comment by Weixuanf** [comment]
ok. this sounds very reasonable, I'm working on it now, should come out soon

**Comment by liulsg** [comment]
Same problem, I dragged the workflow to the workspace and changed the flow, only to find that the default workflow saved was changed. Sometimes I habitually purge processes from my workspace, which leads to some of the processes I created being destroyed.

**Comment by camoody1** [comment]
This feature is SOOOOO much needed. This current autosave is a painful design. I'm constantly living in fear that I'm going to accidentally overwrite one of my large workflows. A standard New/Load/Save system is definitely the way to go. 👍🏼

**Comment by liulsg** [comment]
好像更新到最新版本还是会自动保存。

**Comment by liulsg** [comment]
It seems that updating to the latest version will automatically update

**Comment by Weixuanf** [comment]
📣 Finally, you can manually save your workflow by either click the 💾 floppy disk icon beside the workflow name or Shift+S shortcut (you can customize this shortcut in Settings) Everytime you save, it will create a new record in Version History (you can access this in the dropdown menu on the left side of the name topbar) You can go back and switch versions in version history. You won't need to worry about losing any changes from now on!

<img width="400" alt="Screenshot 2023-12-29 at 11 28 12 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/06f57d2e-ff89-4d84-80b9-60f572839da9">

Please update and enjoy this new feature! let me know if there is any problems or issues.
Happy New Year!

**Comment by Weixuanf** [comment]
> It seems that updating to the latest version will automatically update

This is a design on purpose, it will still **cache** your latest changes so that you don't lose them when you switch to other workflows. now you can still easily switch to other workflows when you have unsaved changes. 

I can disable auto-saving completely, but you will be forced to choose either save or discard your current changes every time you try to switch to other workflows, it's just not that convenient. 

The current saving is more like just caching your latest changes, but you can easily discard them by clicking "Discard unsaved changes", which will bring you back your last saved version

**Comment by DonBaronFactory** [comment]
Used it after the update and it’s perfect like that. Until i read your post i didn’t notice it was saving in the background … I’m fine with the way it is, at least i can go to another pc now and don’t break nothing with the cached workflow on that client

**Comment by liulsg** [comment]
@Weixuanf Thank you for your hard work.
