### ISSUE TITLE
Bug:   Show the render image in other node

### ISSUE THREAD

**Issue by xueqing0622** [11cafe/comfyui-workspace-manager#56]
Bug:   Show the render image in other node
When I have a workflow with a preview in a workflow that has a rendered image displayed, 
and I switch to another workflow, the node with the same id displays the same preview, even if the node does not have a preview item.
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/114840118/963be644-3c25-4e2a-a34d-203a9293b143)
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/114840118/4fe89de5-3e30-4a1b-b478-d4862d08e72f)

**Comment by Weixuanf** [comment]
seems this is not a issue with workspace manager, but an issue with ComfyUI itself. Hence closing this issue. Feel free to report any other issues
