### ISSUE TITLE
Change/Feature Request: Reposition the Workspace Manager Folder on the Screen

### ISSUE THREAD

**Issue by camoody1** [11cafe/comfyui-workspace-manager#59]
I just need to slightly move the position of your Workspace Manager down a bit on my screen. Its current position interferes with information from Comfy telling me which node a workflow is currently processing. It makes the information unreadable.

![image](https://github.com/11cafe/comfyui-workspace-manager/assets/73725653/9e0c68cb-47df-449f-aa68-93b6d9a94811)

I would like to have your icon and workflow title moved down slightly below the area I am pointing to in this image.

**Comment by Weixuanf** [comment]
hi, please update to the latest version, this feature is just added. you can drag here to adjust the position

<img width="331" alt="Screenshot 2023-12-27 at 11 23 16 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/ab63038b-d70a-482a-8854-1a07242a31ee">

**Comment by camoody1** [comment]
> hi, please update to the latest version, this feature is just added. you can drag here to adjust the position
> 
> <img alt="Screenshot 2023-12-27 at 11 23 16 PM" width="331" src="https://private-user-images.githubusercontent.com/18367033/293142311-ab63038b-d70a-482a-8854-1a07242a31ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NDYxMTQsIm5iZiI6MTcwMzc0NTgxNCwicGF0aCI6Ii8xODM2NzAzMy8yOTMxNDIzMTEtYWI2MzAzOGItZDcwYS00ODJhLTg4NTQtMWEwNzI0MmEzMWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDA2NDMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxMzNlNDBkYWI2MTY5OGI1Njc1YjY1NDdjYjQwZTFjMzBhYzEyZjI0ODM0NGQ3ZTM0M2Y3OGFlZDY4Y2M0N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xftOBb_a7gK9t5kD1h5SojwTNGeuYF_GHxRG8V3GFwY">

Did you just add this AFTER you read my post or was this just ridiculously good timing on my part? I just tested the change, and it's exactly what I needed. Thank you so much.

**Comment by Weixuanf** [comment]
Haha it's a good timing. I added this feature 2 days ago I think :) Thanks for your feedback. Your feedbacks and suggestions are very welcomed and valued ☺️
Merry Christams 🎄
