### ISSUE TITLE
bug: some textbox cover workspace-manager

### ISSUE THREAD

**Issue by Rheron1848** [11cafe/comfyui-workspace-manager#60]
![0XIAInxQQY](https://github.com/11cafe/comfyui-workspace-manager/assets/99803057/76c31a28-61ea-4b60-90b0-b2f45fed2b7a)
![8AWYH1DeY5](https://github.com/11cafe/comfyui-workspace-manager/assets/99803057/5817e92a-4d65-477a-b945-2490302ee037)

The layer of certain nodes' textbox is higher than workspace-manager. It is covered up and cannot display properly,

**Comment by Weixuanf** [comment]
hi, what node are these? could you please let me know the names? It would help me reproduce the bug

**Comment by Weixuanf** [comment]
Hi can you update to latest version and try again now? I increased the z-index value of the drawer, hopefully it can be resolved now!

**Comment by Rheron1848** [comment]
sorry, i noticed your comment just now. I will update and verify if the bug still exists.

**Comment by Rheron1848** [comment]
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/99803057/ef58f485-9678-41d6-8a84-407b36c49820)
It looks like it has been fixed. Thank you very much for your efforts!
