### ISSUE TITLE
UI autoquit bug?

### ISSUE THREAD

**Issue by YacratesWyh** [11cafe/comfyui-workspace-manager#61]
After the folder feature added, if you click on a folder that's not actually existed I don't know why, its auto quit.
I think the code is not scanning a sorted my_workflows folder as it returns different result for two different port I am running, and it causes some bug.

**Comment by YacratesWyh** [comment]
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/8447769/f578a59f-23c7-4ca0-a91c-49a32ad9b30e)
Here, I don't have such new folder in my_workflows. After clicking it it's quit.
Refresh fix it but would quit again if click on the folder.

**Comment by Weixuanf** [comment]
ohhhh so you didn't create "New Folder 2" or "New Folder"? It just randomly appears in your workspace?

Have you restarted your python server after upgrade? If not, please restart python server

**Comment by YacratesWyh** [comment]
<img width="407" alt="image" src="https://github.com/11cafe/comfyui-workspace-manager/assets/8447769/b218aa1d-107e-44cd-bd5c-0d0a9469d90d">
So everytime I click the creating new folder button it creates a folder which is not created in the server. I cannot delete a folder where it's not created I think. Where is workflows hash saved? I may have to delete it manually

**Comment by Weixuanf** [comment]
"it creates a folder which is not created in the server."
the folder is created in the internal data structure and when you move your workflows to it, the folder will be created in /ComfyUI/my_workflows too. In server side there is no folder created, but it shouldn't bring you any problem. 

" I cannot delete a folder where it's not created I think" Are you having trouble when you click "Delete"? What will happen if you click "Delete"? Will it give you any errors?
You should be able to delete and rename the folder as you showed in the screenshot. 

"Where is workflows hash saved?"
Under workspace-manager/db/folders.json but I don't think you should manually mess with these internal db files, the "Delete folder" option in UI should do it for you.

Could you screen record the issues you're encountering to help me understand the problem? Thank you!

**Comment by Weixuanf** [comment]
this is folder's usage demo: https://youtu.be/baF16zPiNhs

**Comment by YacratesWyh** [comment]
https://www.youtube.com/watch?v=dqDY_uXLfA4&feature=youtu.be
When I click the nonexisted folder, it would crashed as video

**Comment by YacratesWyh** [comment]
Is the "folder" a kind of tag instead of creating a subfolder under the dir? It's not creating a folder in the undefined->my_workflows.
Also, it's not scanning the dir, which makes the same json when chossing different saving dir.
As far as I know the call of custom_nodes is only once when you open it, so I guess it should renew its db instead of get all info directly from db.

**Comment by YacratesWyh** [comment]
One more thing, maybe the code is not considering open multiple port in different cmd window, where different save dir may cause conflicts.

**Comment by Weixuanf** [comment]
Which browser is it? Is it Edge? 

interesting, can you press F12 or right click "Inspect" to open the browser console? and when it crashes, can you copy screenshot or copy the console message?

<img width="458" alt="Screenshot 2023-12-29 at 3 55 19 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/04f590ff-d0fb-4c7e-b762-851b7d08d574">

**Comment by YacratesWyh** [comment]
DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'comfyspace' exceeded the quota.
    at wa.update (http://localhost:8080/extensions/comfyui-workspace-manager/workspace-manager-N8do0dQO.js:391:32569)
    at http://localhost:8080/extensions/comfyui-workspace-manager/workspace-manager-N8do0dQO.js:408:96274
    at Jd (http://localhost:8080/extensions/comfyui-workspace-manager/workspace-manager-N8do0dQO.js:40:24283)
    at Ta (http://localhost:8080/extensions/comfyui-workspace-manager/workspace-manager-N8do0dQO.js:40:42409)
    at pI (http://localhost:8080/extensions/comfyui-workspace-manager/workspace-manager-N8do0dQO.js:40:41231)
    at Qo (http://localhost:8080/extensions/comfyui-workspace-manager/workspace-manager-N8do0dQO.js:40:40278)
    at d1 (http://localhost:8080/extensions/comfyui-workspace-manager/workspace-manager-N8do0dQO.js:40:36886)
    at Wo (http://localhost:8080/extensions/comfyui-workspace-manager/workspace-manager-N8do0dQO.js:38:3279)
    at http://localhost:8080/extensions/comfyui-workspace-manager/workspace-manager-N8do0dQO.js:40:34263
console.<computed> @ logging.js:315
mm @ workspace-manager-N8do0dQO.js:40
n.callback @ workspace-manager-N8do0dQO.js:40
Hy @ workspace-manager-N8do0dQO.js:38
l1 @ workspace-manager-N8do0dQO.js:40
Mk @ workspace-manager-N8do0dQO.js:40
uI @ workspace-manager-N8do0dQO.js:40
pI @ workspace-manager-N8do0dQO.js:40
Qo @ workspace-manager-N8do0dQO.js:40
d1 @ workspace-manager-N8do0dQO.js:40
Wo @ workspace-manager-N8do0dQO.js:38
(anonymous) @ workspace-manager-N8do0dQO.js:40
workspace-manager-N8do0dQO.js:38  Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'comfyspace' exceeded the quota.
    at wa.update (http://localhost:8080/extensions/comfyui-workspace-manager/workspace-manager-N8do0dQO.js:391:32569)
    at http://localhost:8080/extensions/comfyui-workspace-manager/workspace-manager-N8do0dQO.js:408:96274
    at Jd (http://localhost:8080/extensions/comfyui-workspace-manager/workspace-manager-N8do0dQO.js:40:24283)
    at Ta (http://localhost:8080/extensions/comfyui-workspace-manager/workspace-manager-N8do0dQO.js:40:42409)
    at pI (http://localhost:8080/extensions/comfyui-workspace-manager/workspace-manager-N8do0dQO.js:40:41231)
    at Qo (http://localhost:8080/extensions/comfyui-workspace-manager/workspace-manager-N8do0dQO.js:40:40278)
    at d1 (http://localhost:8080/extensions/comfyui-workspace-manager/workspace-manager-N8do0dQO.js:40:36886)
    at Wo (http://localhost:8080/extensions/comfyui-workspace-manager/workspace-manager-N8do0dQO.js:38:3279)
    at http://localhost:8080/extensions/comfyui-workspace-manager/workspace-manager-N8do0dQO.js:40:34263

**Comment by Weixuanf** [comment]
"Is the "folder" a kind of tag instead of creating a subfolder under the dir? It's not creating a folder in the undefined->my_workflows."

No subfolder is different from tag because it will actually create a subfolder in /my_workflows. But it will only create the subfolder when you actually save some workflows under that folder. So try to move some workflows into the folder and you will see the folder created in /my_workflows dir

See below is my `/ComfyUI/my_workflows` as you can see it did create the actual subfolders 
<img width="491" alt="Screenshot 2023-12-29 at 4 00 40 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/ced062a0-7dea-45d1-8594-d4011d268e24">

**Comment by Weixuanf** [comment]
got it! I know what's happening then. It's because the localStorage has reached maximum quota (10MB) 
This is a known limitation with localStorage. So We are migrating to IndexDB (200MB+) to store our internal data. Once the migration is down, it shouldn't happen anymore. I'll try to come up with the fix asap

**Comment by YacratesWyh** [comment]
ET http://localhost:8080/workspace/get_db?table=userSettings 400 (Bad Request)
Xf @ workspace-manager-N8do0dQO.js:391
load @ workspace-manager-N8do0dQO.js:391
n @ workspace-manager-N8do0dQO.js:391
FH @ workspace-manager-N8do0dQO.js:391
b @ workspace-manager-N8do0dQO.js:408
(anonymous) @ workspace-manager-N8do0dQO.js:408
Jd @ workspace-manager-N8do0dQO.js:40
Ta @ workspace-manager-N8do0dQO.js:40
d1 @ workspace-manager-N8do0dQO.js:40
Wo @ workspace-manager-N8do0dQO.js:38
pI @ workspace-manager-N8do0dQO.js:40
Qo @ workspace-manager-N8do0dQO.js:40
Ak @ workspace-manager-N8do0dQO.js:40
P @ workspace-manager-N8do0dQO.js:25
I @ workspace-manager-N8do0dQO.js:25
workspace-manager-N8do0dQO.js:391 
        
        
        POST http://localhost:8080/workspace/get_system_dir 500 (Internal Server Error)
gv @ workspace-manager-N8do0dQO.js:391
load @ workspace-manager-N8do0dQO.js:391
await in load(异步)
n @ workspace-manager-N8do0dQO.js:391
FH @ workspace-manager-N8do0dQO.js:391
b @ workspace-manager-N8do0dQO.js:408
(anonymous) @ workspace-manager-N8do0dQO.js:408
Jd @ workspace-manager-N8do0dQO.js:40
Ta @ workspace-manager-N8do0dQO.js:40
d1 @ workspace-manager-N8do0dQO.js:40
Wo @ workspace-manager-N8do0dQO.js:38
pI @ workspace-manager-N8do0dQO.js:40
Qo @ workspace-manager-N8do0dQO.js:40
Ak @ workspace-manager-N8do0dQO.js:40
P @ workspace-manager-N8do0dQO.js:25
I @ workspace-manager-N8do0dQO.js:25
logging.js:315 [logging] extension init
logging.js:315 Latest release version: v0.6.0
logging.js:315 [🐍 pysssss] Skipping LinkRenderMode as core extension found
logging.js:315 'IPAdapterApply' optional input 'attn_mask' unmatched
logging.js:315 'ADE_AnimateDiffLoaderWithContext' optional input 'motion_lora' unmatched
logging.js:315 'ADE_AnimateDiffLoaderWithContext' optional input 'motion_model_settings' unmatched
logging.js:315 'VHS_VideoCombine' optional input 'audio' unmatched
logging.js:315 'Reroute' optional input '' unmatched
logging.js:315 'ControlNetLoaderAdvanced' optional input 'timestep_keyframe' unmatched
view:1 
        
        
        GET http://localhost:8080/view?filename=1215_Keyframe%255CVideo_00003.png&type=input&subfolder=&rand=0.6929006252786065 404 (Not Found)
Image(异步)
showImage @ widgets.js:313
(anonymous) @ widgets.js:361
requestAnimationFrame(异步)
IMAGEUPLOAD @ widgets.js:359
ComfyNode @ app.js:1417
createNode @ litegraph.core.js:435
LGraph.configure @ litegraph.core.js:2215
LGraph.configure @ app.js:1249
LGraph.configure @ reroutePrimitive.js:14
LGraph.configure @ snapToGrid.js:53
loadGraphData @ app.js:1599
await in loadGraphData(异步)
app.loadGraphData @ undoRedo.js:23
Rgthree.app.loadGraphData @ rgthree.js:280
setup @ app.js:1348
view:1 
        
        
        GET http://localhost:8080/view?filename=Upscaled+Video_00001.mp4&subfolder=&type=output&format=video%2Fh264-mp4&force_size=256x%3F 404 (Not Found)
view:1 
        
        
        GET http://localhost:8080/view?frame_load_cap=0&skip_first_frames=0&force_rate=0&filename=Video+Location+Here&type=path&format=video%2FVideo+Location+Here&select_every_nth=1&force_size=256x%3F 400 (Bad Request)
:8080/view?filename=1215_hotshotxl%5CVideo_2_00002.mp4&subfolder=&type=output&format=video%2Fh264-mp4&force_size=256x%3F:1 
        
        
        GET http://localhost:8080/view?filename=1215_hotshotxl%5CVideo_2_00002.mp4&subfolder=&type=output&format=video%2Fh264-mp4&force_size=256x%3F 404 (Not Found)

**Comment by Weixuanf** [comment]
@YacratesWyh Hi I just published the new version: https://github.com/11cafe/comfyui-workspace-manager/pull/64
this should solve the UI crash problem, please update and let me know if this works for you or not! Thank you!

**Comment by YacratesWyh** [comment]
So, is it reading the folder in #64 ？I have a bunch of json files created by my colleagues via listen port and they are not read.
<img width="287" alt="image" src="https://github.com/11cafe/comfyui-workspace-manager/assets/8447769/5565b33d-f730-47cc-a0ee-808b5cacf0bb">
<img width="387" alt="image" src="https://github.com/11cafe/comfyui-workspace-manager/assets/8447769/7257d631-4cff-4298-b3dc-433b431fe3b2">

**Comment by Weixuanf** [comment]
@YacratesWyh hi right now the disk folder is one way sync, meaning that we can only write json files into that folder but cannot read any new files you added to it. Please use the Import button to import any new files into your workspace:
<img width="239" alt="Screenshot 2024-01-08 at 5 10 18 PM" src="https://github.com/11cafe/comfyui-workspace-manager/assets/18367033/6b86a585-f035-4c2e-ba3c-9899848a2f55">

We do have the plan to add reading folders from your disk and add the files into your workspace automatically. Once I have that update, I will let you know :)

**Comment by YacratesWyh** [comment]
<img width="301" alt="image" src="https://github.com/11cafe/comfyui-workspace-manager/assets/8447769/b3a6d579-2498-41de-8555-6f31cab1a683">
It would import exactly same json twice. Maybe it needs a hash file.

**Comment by YacratesWyh** [comment]
> how did you import? I just tried bulk import and it worked fine: https://youtu.be/YrOuzgyEzpI

You made the same feature! As it shows in your video, if you import the same json file, it would just import it without checking whether it is in the db.
Like, I have av1.json, others create av2.json, but they are the same name as a.json, Icannot tell the difference, and already import av1.json. So I have to import 2json, as a 2.v1.json, and a 3.v2.json and a.v1.json

**Comment by YacratesWyh** [comment]
And as time goes on, this same copy would go crazy more, and I wonder if it could check and wouldn't import a 2.v1.json

**Comment by Weixuanf** [comment]
Ok, it seems you are trying to open an existing workflow that already existed in your workspace. In that case, why not just find it in your workspace and click open to open it up? 
The function of import is to let you select some json/image files in your computer and add it your workspace (this will create a new workflow with the json data you selected)

I feel like to achieve what you want, we need to add a check after you selected file from your computer, if it's already recorded in the workspace, we just open it up, otherwise we create new. ⬅️ this may be able to achieved,but need some work

**Comment by YacratesWyh** [comment]
The problem is caused by minus modifying a json file, it would output 2 different files and saved as 2 file. Let's say, I made a template of a json, and I would use it in my local port, and share it via a listen port, my colleague would change it when he produces his imgs, and produce a copy of json which produces unevitable copy. The workflow folder would grow as large as the otuput folder, where I usually organize it by date. The workflow folder would grow to a 100more json in a week, and I need to sort and figure out template in about 2 hours. In such case, it would be even better to use directly the output image as json, because you need to import it, and the best way to import is to check the image instead of a string name.
Anyway, I would ask everyone to make template daily and organize output carefully as usual. It's my business but I just want to tell you my user experience.

**Comment by Weixuanf** [comment]
sorry I'm having a hard time understanding your work routines, seems like some collaborations steps. 

Could you add me on wechat or discord or any other communication channel you prefer, I need to talk with you to learn about your everyday routine to find out a good approach to solve this.

my wechat: wxkkk23333
my discord: briefpeach

thank you, sorry for the inconvenience, i hope we can make this experience better for you and your colleague!
