### ISSUE TITLE
[Bug/Feature Request] Previews are saved as nonexistant images

### ISSUE THREAD

**Issue by SampleTexting** [11cafe/comfyui-workspace-manager#71]
All of my previews are getting saved into the gallery as a noneexistant images.  
Would it be possible to explicitly deny the temp path where previews are saved? Or alternatively if that's not possible, to auto-remove those empty entries from the internal database automatically on a page refresh?
![image](https://github.com/11cafe/comfyui-workspace-manager/assets/155495184/d89cf396-6f43-4b0b-bed7-c87380fa28ea)

**Comment by Weixuanf** [comment]
hi, these bugs are already fixed in https://github.com/11cafe/comfyui-workspace-manager/pull/70
please update your extension to latest version and you will see it fixed

**Comment by SampleTexting** [comment]
Thank you! Hadn't noticed there was an update for it! Can confirm all is working as its supposed to now.
