### ISSUE TITLE
Workflows do not respect the sorting rules

### ISSUE THREAD

**Issue by bkutasi** [11cafe/comfyui-workspace-manager#73]
Ive noticed that sometimes the sorting is broken and it is not alphabetical/reversed and only takes the update time as primary sorting metric. I've noticed this mainly with workflows inside the folders, but outside aswell.
My main solution is to just take out the nodes and re-add them in the right order to the folders. This is also another metric that is not in the sorting parameters, maybe moving around workflows count as modifying them.

**Comment by Weixuanf** [comment]
Hi thanks for reporting this bug. I have to admit the current folder functionality does have some problems. It’s on our plan to fix folders.

**Comment by Weixuanf** [comment]
hi this should be fixed by https://github.com/11cafe/comfyui-workspace-manager/pull/85

update the extension and see if it works for you, thank you

**Comment by bkutasi** [comment]
Had some time to check it out, and it works! Thanks!
