### ISSUE TITLE
Allow import Folder workflows with an auto-folder

### ISSUE THREAD

**Issue by rafstahelin** [11cafe/comfyui-workspace-manager#87]
I have a bunch of workflows bundled in folders got cloned on my disk. 
It would be nice to automatically import all those folders recursively, so if I have DrData's Impact and Inspire subfolders, the script will add the folder structure 
Maybe just two levels down at least

**Comment by Weixuanf** [comment]
You mean read the sub folders and content from your disk to workspace and auto adding new workflows added in your disk? It’s like a two way sync (import export ) We’re working on this right now and will come soon

**Comment by rafstahelin** [comment]
Yes correct. 

Also, I work between my desktop and my laptop. How do I keep them up to date? If I add new workflows in one, best way to mirror in the other? Manual import/export? Or can I simply sync the my_workflows folder on my Dropbox?.
