### ISSUE TITLE
Export entire library of workflows

### ISSUE THREAD

**Issue by rafstahelin** [11cafe/comfyui-workspace-manager#89]
Need a way to synk my workflows between devices 

Is there a way or is the only way to do it is to export all workflows ?

**Comment by Weixuanf** [comment]
Hi I’m planning to enable cloud sync in future so you can have your entire workspace backed up and synced to cloud and access from any device.  you can also share it with other people via links. Like google docs or Figma. Make it easy to collaborate with your team. 🙂

but this will take some time…
