### ISSUE TITLE
Save Workflow Graph Image automatically

### ISSUE THREAD

**Issue by rafstahelin** [11cafe/comfyui-workspace-manager#93]
In the workspace one can export the graph image via Workflow Image> export > png
It would be nice to have an button to automatically create the png and to preview it

**Comment by gisu** [comment]
Furthermore, the preview images should be saved in a separate folder, because I, at least, often empty the output folder. The image of the workflow should also be fixed once it has been created, I can update it manually if I want.

**Comment by rafstahelin** [comment]
I second that. Please make this a priority along with the import workflows recursively from folders with the folder names

**Comment by Weixuanf** [comment]
“the preview images should be saved in a separate folder, “

do you mean we should save a copy of the files in your output folder? I worry that would be too many duplicated image files for some people who don’t usually empty or change their output folder. And take up their disk storage 

we can let you choose to sync your images to cloud storage automatically, that way you can access it forever and anywhere, from any device. they will be private of course, unless you choose to publish them

**Comment by rafstahelin** [comment]
Well, yes to saving to Dropbox. Which is already something you allow. We can already decide where to save workflows. 

In my case, I'd like to use a Symlink to reference the Dropbox folder. Would that be possible?
Symlink in Comfy root referencing my workflow folder in my Dropbox

**Comment by rafstahelin** [comment]
Regarding preview. 

Why not just offer png screenshot of the workflow like I said above--save workflow to png image that way there is no side car image folder 

That's how I would use workflows

**Comment by Weixuanf** [comment]
> Well, yes to saving to Dropbox. Which is already something you allow. We can already decide where to save workflows.
> 
> In my case, I'd like to use a Symlink to reference the Dropbox folder. Would that be possible? Symlink in Comfy root referencing my workflow folder in my Dropbox

Link to Dropbox cloud folder is probably very difficult. Because we don’t have your login authorization to be able to request your private data from Dropbox…

**Comment by rafstahelin** [comment]
No I dont mean that
I just mean a “symlink” 

There’s no logging


thanks, 
warmest regards,

𝐑⒜𝐟 𝕊t𝐚ｈⅇl i𝘯

**Comment by Weixuanf** [comment]
Oh interesting I don’t have too much knowledge on symlink, I’ll need to research it a bit!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rafstahelin** [comment]
At any rate, not very important. 
More important is the recursive import with folder creation, and the screenshot auto-save

thanks, 
warmest regards,

𝐑⒜𝐟 𝕊t𝐚ｈⅇl i𝘯

**Comment by mr-asa** [comment]
I'll add my perspective on the problem with the previews. 
I also think it would be good to save previews to a separate directory. In the same \db/icons folder, for example. If there is a fear of duplicates and saving disk space, it would be enough to save previews of images in 128 pixels resolution (as they are visible in the plugin panel). 
I find it convenient to save space without the risk of losing the previews (because I lost them immediately, as I deleted all the unnecessary), and there is a possibility to replace the preview file even manually, leaving the same name.

**Comment by Amorano** [comment]
There should be an option to completely ignore saving the workflow images.
